import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { api } from "../lib/api";

type ProfileSummary = { profile: { displayName: string; age: number; city: string | null; bio: string | null; profileImages: string[]; visibility: string }; completion: number };

export default function Account() {
  const { user, signOut } = useAuth(); const navigate = useNavigate(); const [summary, setSummary] = useState<ProfileSummary | null>(null);
  useEffect(() => { api<ProfileSummary>("/profile/me").then(setSummary).catch(() => undefined); }, []);
  async function logout() { await signOut(); navigate("/"); }
  const completion = summary?.completion ?? 0; const profile = summary?.profile; const displayName = profile?.displayName ?? user?.displayName ?? "there";
  return <section className="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-12 lg:px-10 lg:py-16">
    <div className="overflow-hidden rounded-[1.75rem] bg-plum text-cream shadow-soft sm:rounded-[2rem]"><div className="relative grid gap-7 px-5 py-7 sm:gap-10 sm:px-10 sm:py-9 lg:grid-cols-[1.2fr_.8fr] lg:px-14 lg:py-12"><div className="absolute -right-24 -top-32 h-80 w-80 rounded-full border border-gold/20" /><div className="absolute -bottom-40 right-24 h-96 w-96 rounded-full border border-cream/10" /><div className="relative"><p className="text-xs uppercase tracking-[0.35em] text-gold">Your private space</p><h1 className="mt-4 max-w-xl font-display text-4xl leading-[1.05] sm:text-6xl">Welcome, {displayName}.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-cream/70 sm:mt-5 sm:text-base sm:leading-7">A quieter place to meet people who value real conversation. Your profile is yours to shape, reveal, and keep private.</p><div className="mt-6 flex gap-3 sm:mt-8 sm:flex-wrap"><Link to="/app/profile" className="flex-1 rounded-full bg-cream px-4 py-3 text-center text-sm font-semibold text-burgundy hover:bg-white sm:flex-none sm:px-5">Complete profile</Link><Link to="/app/discover" className="flex-1 rounded-full border border-cream/25 px-4 py-3 text-center text-sm font-semibold text-cream hover:bg-white/10 sm:flex-none sm:px-5">Find people</Link></div></div><div className="relative flex items-end justify-start lg:justify-end"><div className="w-full max-w-xs rounded-3xl border border-cream/15 bg-cream/10 p-5 backdrop-blur-sm"><div className="flex items-end justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-gold">Profile strength</p><p className="mt-2 font-display text-5xl">{completion}%</p></div><span className="text-xs text-cream/55">{profile?.visibility === "VISIBLE" ? "Visible" : "Private"}</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-cream/15"><div className="h-full rounded-full bg-gold transition-all" style={{ width: `${completion}%` }} /></div><p className="mt-4 text-sm leading-6 text-cream/60">{completion >= 60 ? "Your introduction is ready to be discovered." : "Add a photo and a little about yourself to be seen."}</p></div></div></div></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-3"><Link to="/app/profile" className="group rounded-3xl border border-charcoal/10 bg-white/75 p-6 shadow-soft transition hover:-translate-y-0.5 hover:border-burgundy/25"><p className="text-xs uppercase tracking-[0.22em] text-burgundy/65">01 · Introduction</p><h2 className="mt-3 font-display text-2xl">Shape your profile</h2><p className="mt-2 text-sm leading-6 text-charcoal/60">Tell people what makes a good conversation for you.</p><span className="mt-5 block text-sm font-semibold text-burgundy">Edit profile →</span></Link><Link to="/app/discover" className="group rounded-3xl border border-charcoal/10 bg-white/75 p-6 shadow-soft transition hover:-translate-y-0.5 hover:border-burgundy/25"><p className="text-xs uppercase tracking-[0.22em] text-burgundy/65">02 · Explore</p><h2 className="mt-3 font-display text-2xl">Find people quietly</h2><p className="mt-2 text-sm leading-6 text-charcoal/60">Browse members and find conversations that feel natural.</p><span className="mt-5 block text-sm font-semibold text-burgundy">Start finding people →</span></Link><Link to="/settings/account" className="group rounded-3xl border border-charcoal/10 bg-white/75 p-6 shadow-soft transition hover:-translate-y-0.5 hover:border-burgundy/25"><p className="text-xs uppercase tracking-[0.22em] text-burgundy/65">03 · Control</p><h2 className="mt-3 font-display text-2xl">Your boundaries</h2><p className="mt-2 text-sm leading-6 text-charcoal/60">Manage visibility, privacy, notifications, and security.</p><span className="mt-5 block text-sm font-semibold text-burgundy">Open settings →</span></Link></div>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t border-charcoal/10 pt-6"><p className="text-sm text-charcoal/55">{user?.isEmailVerified ? "Your email is verified." : "Please verify your email to continue."} Keep what matters private.</p><div className="flex flex-wrap gap-4 text-sm"><Link to="/membership" className="font-semibold text-burgundy">View membership</Link><button type="button" onClick={() => void logout()} className="font-semibold text-burgundy">Sign out</button></div></div>
  </section>;
}
