import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../lib/api";

type Stats = Record<string, number | string>;
const cardNames = [["totalUsers", "Total users"], ["activeUsers", "Active users"], ["men", "Men"], ["women", "Women"], ["verifiedUsers", "Verified users"], ["activeSubscribers", "Active subscribers"], ["monthlyRevenue", "Monthly revenue"], ["totalRevenue", "Total revenue"], ["newUsers", "New users"], ["reports", "Open reports"], ["activeMatches", "Active matches"]];
function useAdmin<T>(path: string, initial: T) { const [data, setData] = useState<T>(initial); const [error, setError] = useState(""); useEffect(() => { api<T>(path).then(setData).catch((e) => setError(e.message)); }, [path]); return { data, error }; }
function ErrorText({ error }: { error: string }) { return error ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p> : null; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl bg-white/80 p-5 shadow-soft"><h2 className="mb-4 font-display text-2xl">{title}</h2>{children}</section>; }

export function AdminDashboard() { const { data, error } = useAdmin<Stats>("/admin/stats", {}); return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cardNames.map(([key, label]) => <div key={key} className="rounded-2xl border border-charcoal/10 bg-white/75 p-5"><p className="text-xs uppercase tracking-widest text-charcoal/50">{label}</p><p className="mt-3 font-display text-3xl text-burgundy">{data[key] ?? "-"}</p></div>)}<div className="sm:col-span-2 lg:col-span-3"><ErrorText error={error} /></div></div>; }

type User = { id: string; email: string; displayName: string; gender: string; status: string; isEmailVerified: boolean; city?: string };
export function AdminUsers() { const [search, setSearch] = useState(""); const [reload, setReload] = useState(0); const { data, error } = useAdmin<{ users: User[]; pagination: { total: number } }>(`/admin/users?search=${encodeURIComponent(search)}`, { users: [], pagination: { total: 0 } }); useEffect(() => { if (reload) window.location.reload(); }, [reload]); async function changeStatus(id: string, status: string) { await api(`/admin/users/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }); setReload((v) => v + 1); } return <Section title="Users"><div className="mb-4 flex gap-2"><input className="profile-input mt-0" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, email or city" /><button className="rounded-xl bg-burgundy px-4 text-sm text-cream" onClick={() => setSearch(search)}>Search</button></div><ErrorText error={error} /><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-charcoal/10 text-charcoal/50"><th className="p-3">Member</th><th className="p-3">Status</th><th className="p-3">Verified</th><th className="p-3">Actions</th></tr></thead><tbody>{data.users.map((user) => <tr key={user.id} className="border-b border-charcoal/5"><td className="p-3"><Link className="font-semibold text-burgundy" to={`/admin/users/${user.id}`}>{user.displayName}</Link><div className="text-xs text-charcoal/50">{user.email}</div></td><td className="p-3">{user.status}</td><td className="p-3">{user.isEmailVerified ? "Yes" : "No"}</td><td className="flex gap-2 p-3"><button className="text-xs text-burgundy" onClick={() => changeStatus(user.id, user.status === "SUSPENDED" || user.status === "BANNED" ? "ACTIVE" : "SUSPENDED")}>{user.status === "SUSPENDED" || user.status === "BANNED" ? "Restore" : "Suspend"}</button><button className="text-xs text-red-700" onClick={() => changeStatus(user.id, "BANNED")}>Ban</button></td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-charcoal/50">{data.pagination.total} members</p></Section>; }

export function AdminUserDetail() { const { userId } = useParams(); const { data, error } = useAdmin<any>(`/admin/users/${userId}`, {}); return <Section title="User details"><ErrorText error={error} />{data.user && <div className="space-y-3 text-sm"><p><strong>{data.user.displayName}</strong> · {data.user.email}</p><p>{data.user.gender} · {data.user.city ?? "No city"} · {data.user.status}</p><p>Email verified: {data.user.isEmailVerified ? "Yes" : "No"}</p><div className="flex gap-3"><button className="rounded-full bg-burgundy px-4 py-2 text-sm text-cream" onClick={() => api(`/admin/users/${userId}/verify-profile`, { method: "POST" }).then(() => window.location.reload())}>Verify profile</button><Link className="rounded-full border border-charcoal/15 px-4 py-2" to="/admin/users">Back to users</Link></div><h3 className="pt-5 font-semibold">Subscriptions ({data.subscriptions?.length ?? 0})</h3>{data.subscriptions?.map((s: any) => <p key={s.id} className="text-charcoal/70">{s.plan.name}: {s.status}, ends {s.endDate ? new Date(s.endDate).toLocaleDateString() : "-"}</p>)}</div>}</Section>; }

export function AdminList({ kind }: { kind: "subscriptions" | "payments" | "reports" }) { const { data, error } = useAdmin<any>(`/admin/${kind}`, { [kind]: [] }); const items = data[kind] ?? []; return <Section title={kind[0].toUpperCase() + kind.slice(1)}><ErrorText error={error} /><div className="space-y-2">{items.map((item: any) => <div key={item.id} className="rounded-2xl border border-charcoal/10 p-4 text-sm"><strong>{item.user?.displayName ?? item.reporter?.displayName ?? item.reason ?? item.id}</strong><span className="ml-3 text-charcoal/60">{item.status}</span>{item.amount && <span className="ml-3">{item.currency} {item.amount}</span>}{kind === "subscriptions" && <span className="float-right flex gap-2"><button className="text-xs text-burgundy" onClick={() => api(`/admin/subscriptions/${item.id}/extend`, { method: "PATCH", body: JSON.stringify({ months: 1 }) }).then(() => window.location.reload())}>Extend 1 month</button><button className="text-xs text-red-700" onClick={() => api(`/admin/subscriptions/${item.id}/cancel`, { method: "PATCH" }).then(() => window.location.reload())}>Cancel</button></span>}{kind === "reports" && <select className="float-right rounded border p-1 text-xs" value={item.status} onChange={(e) => api(`/admin/reports/${item.id}`, { method: "PATCH", body: JSON.stringify({ status: e.target.value }) }).then(() => window.location.reload())}>{["PENDING", "REVIEWED", "RESOLVED", "DISMISSED"].map((s) => <option key={s}>{s}</option>)}</select>}</div>)}</div></Section>; }

export function AdminPlans() { const { data, error } = useAdmin<any>("/admin/plans", { plans: [] }); const [form, setForm] = useState({ name: "", durationMonths: 1, price: 0, featured: false, active: true }); async function create() { await api("/admin/plans", { method: "POST", body: JSON.stringify(form) }); window.location.reload(); } async function edit(plan: any) { const name = window.prompt("Plan name", plan.name); const price = window.prompt("Price", plan.price); if (name && price) { await api(`/admin/plans/${plan.id}`, { method: "PATCH", body: JSON.stringify({ name, price: Number(price) }) }); window.location.reload(); } } return <Section title="Plans"><ErrorText error={error} /><div className="mb-5 grid gap-2 sm:grid-cols-5">{["name", "durationMonths", "price"].map((key) => <input key={key} className="profile-input mt-0" placeholder={key} value={(form as any)[key]} onChange={(e) => setForm({ ...form, [key]: key === "name" ? e.target.value : Number(e.target.value) })} />)}<button className="rounded-xl bg-burgundy px-3 text-sm text-cream" onClick={create}>Create plan</button></div>{data.plans.map((plan: any) => <div key={plan.id} className="flex items-center justify-between border-b border-charcoal/10 py-3 text-sm"><span>{plan.name} · {plan.durationMonths} month(s) · {plan.currency} {plan.price}</span><span className="flex gap-3"><button className="text-burgundy" onClick={() => edit(plan)}>Edit</button><button className="text-burgundy" onClick={() => api(`/admin/plans/${plan.id}`, { method: "PATCH", body: JSON.stringify({ active: !plan.active }) }).then(() => window.location.reload())}>{plan.active ? "Deactivate" : "Activate"}</button></span></div>)}</Section>; }

export function AdminSettings() { const { data, error } = useAdmin<any>("/admin/settings", { settings: {} }); const [settings, setSettings] = useState<any>(null); useEffect(() => { if (data.settings && !settings) setSettings(data.settings); }, [data, settings]); if (!settings) return <Section title="Settings">Loading...</Section>; return <Section title="Settings"><ErrorText error={error} /><div className="grid gap-3 sm:grid-cols-2">{Object.entries(settings).map(([key, value]) => <label key={key} className="text-sm capitalize">{key.replace(/[A-Z]/g, (c) => ` ${c}`)}<input className="profile-input" value={String(value)} onChange={(e) => setSettings({ ...settings, [key]: key === "membershipMode" || key === "siteName" || key === "supportEmail" ? e.target.value : Number(e.target.value) })} /></label>)}</div><button className="mt-5 rounded-xl bg-burgundy px-5 py-3 text-sm text-cream" onClick={() => api("/admin/settings", { method: "PUT", body: JSON.stringify(settings) })}>Save settings</button></Section>; }
