import { Link } from "react-router-dom";

const pillars = [["01", "Privacy without performance", "Your profile is yours to shape. We keep the experience discreet from the first hello."], ["02", "Conversations with intention", "A slower, more thoughtful way to discover people who are looking for something real."], ["03", "Boundaries that stay visible", "Verification, controls, blocking, and reporting are built into the experience."]];

export default function Home() {
  return <>
    <section className="relative mx-auto grid min-h-[680px] max-w-7xl items-center gap-14 px-6 py-20 lg:grid-cols-[1.02fr_0.98fr] lg:px-10 lg:py-24"><div className="absolute -left-28 top-16 h-72 w-72 rounded-full bg-rose/15 blur-3xl" /><div className="relative"><p className="mb-6 text-xs uppercase tracking-[0.35em] text-burgundy/70">Private conversations, meaningful connections</p><h1 className="max-w-2xl font-display text-6xl leading-[.98] tracking-tight text-charcoal sm:text-8xl">Some things begin with a <em className="text-burgundy">whisper.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-charcoal/68">A discreet space for adults to discover, connect, and have meaningful private conversations.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/register" className="rounded-full bg-burgundy px-7 py-3.5 text-sm font-semibold text-cream shadow-soft transition hover:-translate-y-0.5 hover:bg-plum">Create account</Link><Link to="/login" className="rounded-full border border-charcoal/15 bg-white/60 px-7 py-3.5 text-sm font-semibold transition hover:border-burgundy/30 hover:text-burgundy">Sign in</Link></div><p className="mt-6 text-xs uppercase tracking-[0.2em] text-charcoal/45">Private · Secure · 18+ Members Only</p></div><div className="relative mx-auto w-full max-w-md"><div className="aspect-[4/5] rotate-2 rounded-[2.5rem] bg-gradient-to-br from-plum via-burgundy to-rose p-3 shadow-soft"><div className="relative flex h-full flex-col justify-between overflow-hidden rounded-[2rem] border border-cream/20 bg-gradient-to-br from-charcoal/35 to-plum/20 p-7 text-cream"><div className="absolute -right-16 top-20 h-56 w-56 rounded-full border border-gold/30" /><div className="absolute -bottom-20 -left-12 h-64 w-64 rounded-full border border-cream/15" /><p className="relative text-xs uppercase tracking-[0.3em] text-gold">A space of your own</p><div className="relative"><p className="font-display text-4xl leading-tight">The best conversations have a little room around them.</p><p className="mt-5 text-sm leading-6 text-cream/65">Take your time. Be curious. Keep what matters private.</p></div><div className="relative flex items-center justify-between border-t border-cream/15 pt-5 text-xs text-cream/55"><span>Discover quietly</span><span>SH / 01</span></div></div></div></div></section>
    <section className="border-y border-charcoal/10 bg-white/45"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-[.75fr_1.25fr] lg:px-10"><div><p className="text-xs uppercase tracking-[0.3em] text-burgundy/65">The idea</p><h2 className="mt-4 font-display text-4xl leading-tight sm:text-5xl">Connection does not need an audience.</h2></div><p className="max-w-2xl text-lg leading-8 text-charcoal/65">Sshh... Koi Hai? is built for the part of meeting someone that happens after the noise falls away. A considered profile, an intentional interest, and a private conversation when it feels right.</p></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs uppercase tracking-[0.3em] text-burgundy/65">Why here</p><div className="mt-10 grid gap-5 lg:grid-cols-3">{pillars.map(([number, title, copy]) => <article key={number} className="rounded-3xl border border-charcoal/10 bg-white/65 p-7 transition hover:-translate-y-1 hover:shadow-soft"><span className="font-display text-3xl text-gold">{number}</span><h3 className="mt-12 font-display text-2xl">{title}</h3><p className="mt-4 text-sm leading-7 text-charcoal/62">{copy}</p></article>)}</div></section>
    <section className="bg-plum text-cream"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-[1fr_1fr] lg:items-center lg:px-10"><div><p className="text-xs uppercase tracking-[0.3em] text-gold">How it works</p><h2 className="mt-5 max-w-xl font-display text-5xl leading-tight">Make space for a better hello.</h2><Link to="/how-it-works" className="mt-8 inline-flex rounded-full border border-cream/30 px-6 py-3 text-sm hover:border-gold hover:text-gold">See the rhythm</Link></div><div className="space-y-4 text-sm text-cream/65"><p className="border-b border-cream/15 pb-5"><strong className="mr-4 font-normal text-gold">01</strong> Create your space with the details that feel right.</p><p className="border-b border-cream/15 pb-5"><strong className="mr-4 font-normal text-gold">02</strong> Discover members with compatible intentions.</p><p><strong className="mr-4 font-normal text-gold">03</strong> Let mutual interest open a private conversation.</p></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="grid gap-10 rounded-[2rem] border border-gold/25 bg-gold/10 p-8 sm:p-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs uppercase tracking-[0.3em] text-burgundy/65">Membership</p><h2 className="mt-4 font-display text-4xl">A considered experience for grown-up connections.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-charcoal/65">Simple plans, clear terms, and a platform designed around privacy. Membership options will be shared clearly at launch.</p></div><Link to="/membership" className="rounded-full bg-burgundy px-6 py-3 text-center text-sm font-semibold text-cream">Explore membership</Link></div></section>
    <section className="border-y border-charcoal/10 bg-white/40"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="text-xs uppercase tracking-[0.3em] text-burgundy/65">Trust, quietly</p><h2 className="mt-4 font-display text-4xl">Your comfort is part of the product.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-cream p-5"><h3 className="font-display text-xl">Verified adults</h3><p className="mt-2 text-sm leading-6 text-charcoal/60">Email verification and server-side 18+ validation.</p></div><div className="rounded-2xl bg-cream p-5"><h3 className="font-display text-xl">Your controls</h3><p className="mt-2 text-sm leading-6 text-charcoal/60">Privacy settings, blocking, and reporting built in.</p></div></div></div></section>
    <section className="mx-auto max-w-3xl px-6 py-24"><p className="text-center text-xs uppercase tracking-[0.3em] text-burgundy/65">Frequently asked</p><h2 className="mt-4 text-center font-display text-4xl">A few quiet answers.</h2><div className="mt-10 space-y-3">{[["Is Sshh... Koi Hai? only for adults?", "Yes. The platform is for adults aged 18 and above, with server-side date-of-birth validation and email verification."], ["Will my exact date of birth be public?", "No. Exact dates of birth are not part of the public profile experience."], ["Can I control who contacts me?", "Privacy, blocking, and reporting controls are core parts of the product as the member experience grows."]].map(([question, answer]) => <details key={question} className="group rounded-2xl border border-charcoal/10 bg-white/55 p-5"><summary className="cursor-pointer list-none font-display text-xl">{question}<span className="float-right text-burgundy transition group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-sm leading-7 text-charcoal/62">{answer}</p></details>)}</div></section>
    <section className="bg-burgundy text-cream"><div className="mx-auto max-w-7xl px-6 py-20 text-center lg:px-10"><p className="text-xs uppercase tracking-[0.3em] text-gold">When you are ready</p><h2 className="mx-auto mt-5 max-w-2xl font-display text-5xl leading-tight">Some conversations are meant to stay private.</h2><Link to="/register" className="mt-8 inline-flex rounded-full bg-cream px-7 py-3.5 text-sm font-semibold text-burgundy hover:bg-white">Create your account</Link></div></section>
  </>;
}
