import { useEffect } from "react";
import { Link } from "react-router-dom";

const intentions = ["Meaningful conversation", "Companionship", "A private connection", "Friendship", "Something intentional", "Someone who understands"];
const trustPoints = [["Privacy in your control", "Choose what your profile reveals and keep your personal life out of the spotlight."], ["Mutual by design", "An interest is only the beginning. Private chat opens after the other person accepts."], ["Boundaries included", "Email verification, profile controls, blocking, reporting, and account deletion are built in."]];

function MemberPreview() {
  return <div className="relative mx-auto w-full max-w-md lg:ml-auto"><div className="absolute -inset-5 rounded-[2.5rem] border border-gold/20" /><div className="relative rounded-[2rem] border border-cream/15 bg-cream/[.07] p-3 shadow-soft backdrop-blur"><div className="rounded-[1.5rem] border border-cream/10 bg-charcoal/45 p-5 sm:p-6"><div className="flex items-start justify-between gap-4 border-b border-cream/10 pb-5"><div><p className="eyebrow text-gold">Member view</p><p className="mt-2 font-display text-2xl">Discover at your pace</p></div><span className="rounded-full border border-cream/15 px-3 py-1 text-[10px] text-cream/55">Private</span></div><div className="mt-5 space-y-3">{[["01", "Shared intentions", "See what someone is looking for."], ["02", "A thoughtful introduction", "Start with something real."], ["03", "A mutual yes", "Conversation opens when it feels right."]].map(([number, title, copy]) => <div key={number} className="flex items-center gap-3 rounded-2xl border border-cream/10 bg-cream/[.06] p-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-gold/15 font-display text-lg text-gold">{number}</span><div><p className="text-sm font-semibold text-cream/90">{title}</p><p className="mt-0.5 text-xs text-cream/50">{copy}</p></div><span className="ml-auto text-cream/30">&#8594;</span></div>)}</div><div className="mt-5 flex items-center gap-3 border-t border-cream/10 pt-5"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-gold/20 text-sm text-gold">&#10003;</span><p className="text-xs leading-5 text-cream/60">Your email and private details stay out of the public view.</p></div></div></div></div>;
}

function ExampleProfiles() {
  const profiles = [["Trisha", "38", "Delhi", "A thoughtful and steady relationship", "/demo-profiles/trisha.png"], ["Simran", "34", "Delhi", "Something honest and unhurried", "/demo-profiles/simran.png"], ["Anika", "30", "Mumbai", "A mature relationship built with care", "/demo-profiles/anika-resort.png"]];
  useEffect(() => { profiles.forEach(([, , , , image]) => { const preload = new Image(); preload.src = image; }); }, []);
  return <section className="border-b border-charcoal/10 bg-cream"><div className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-burgundy/65">A glimpse inside</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">People looking for something real.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-charcoal/60">These example profiles show how members can introduce themselves. Real member visibility is always controlled by privacy settings.</p></div><span className="rounded-full border border-charcoal/15 px-4 py-2 text-[10px] uppercase tracking-[0.2em] text-charcoal/50">Example previews</span></div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{profiles.map(([name, age, city, intent, image]) => <article key={name} className="overflow-hidden rounded-3xl border border-charcoal/10 bg-white/75 shadow-sm"><div className="aspect-[4/3] bg-plum"><img src={image} alt="Example member profile" loading="lazy" className="h-full w-full object-cover" /></div><div className="p-5"><h3 className="font-display text-2xl">{name}, {age}</h3><p className="mt-1 text-sm text-charcoal/50">{city}</p><p className="mt-4 text-sm leading-6 text-charcoal/65">{intent}</p><span className="mt-4 inline-flex rounded-full bg-cream px-3 py-1 text-xs text-burgundy">Privacy-aware preview</span></div></article>)}</div></div></section>;
}

export default function Home() {
  return <>
    <section className="relative overflow-hidden bg-plum text-cream"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,rgba(200,169,107,.18),transparent_28%),radial-gradient(circle_at_10%_90%,rgba(183,122,143,.16),transparent_34%)]" /><div className="relative mx-auto grid min-h-[650px] max-w-7xl items-center gap-12 px-6 py-16 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:px-10"><div><p className="eyebrow text-gold">Private connections for adults</p><h1 className="mt-6 max-w-3xl font-display text-5xl leading-[.98] tracking-tight sm:text-7xl lg:text-[5.5rem]">Someone out there wants the <em className="text-gold">same conversation</em> you do.</h1><p className="mt-7 max-w-xl text-base leading-7 text-cream/70 sm:text-lg">Meet adults looking for private, meaningful connections, without putting your personal life on display.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/register" className="rounded-full bg-cream px-7 py-3.5 text-center text-sm font-semibold text-burgundy transition hover:bg-white">See who is here</Link><Link to="/how-it-works" className="rounded-full border border-cream/25 px-7 py-3.5 text-center text-sm font-semibold text-cream transition hover:border-gold hover:text-gold">How it works</Link></div><p className="mt-6 max-w-xl text-xs leading-6 text-cream/50">18+ only · Private profiles · Verified accounts · Mutual connections · You choose who can contact you</p></div><MemberPreview /></div></section>
    <ExampleProfiles />
    <section className="border-b border-charcoal/10 bg-cream"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 lg:grid-cols-[.85fr_1.15fr] lg:px-10"><div><p className="eyebrow text-burgundy/65">The feeling</p><h2 className="mt-4 max-w-xl font-display text-4xl leading-tight sm:text-5xl">There is no need to perform here.</h2></div><p className="max-w-2xl text-base leading-8 text-charcoal/65 sm:text-lg">Start with as much, or as little, as you are comfortable sharing. Discover people by intention, signal interest clearly, and let a mutual yes open the door to a private conversation.</p></div></section>
    <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-burgundy/65">What brings people here</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">Different reasons. The same care.</h2></div><Link to="/register" className="text-sm font-semibold text-burgundy underline underline-offset-4">Create your profile &#8594;</Link></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{intentions.map((item, index) => <div key={item} className="surface-card flex items-center gap-4 rounded-2xl px-5 py-5"><span className="font-display text-xl text-gold">0{index + 1}</span><span className="text-sm text-charcoal/75">{item}</span></div>)}</div></section>
    <section className="bg-charcoal text-cream"><div className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="max-w-2xl"><p className="eyebrow text-gold">A simple rhythm</p><h2 className="mt-4 font-display text-4xl leading-tight sm:text-5xl">Private conversations start with mutual interest.</h2></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-cream/10 bg-cream/10 md:grid-cols-3">{[["01", "Create your space", "Build a profile that sounds like you. Your email stays private."], ["02", "Discover thoughtfully", "Explore compatible intentions and people at a comfortable pace."], ["03", "Connect when it feels right", "Send an interest. Chat opens only after the other person accepts."]].map(([number, title, copy]) => <article key={number} className="bg-charcoal p-7"><span className="font-display text-3xl text-gold">{number}</span><h3 className="mt-12 font-display text-2xl">{title}</h3><p className="mt-4 text-sm leading-7 text-cream/60">{copy}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="grid gap-5 lg:grid-cols-3">{trustPoints.map(([title, copy], index) => <article key={title} className="surface-card rounded-3xl p-7"><p className="eyebrow text-burgundy/60">Trust / 0{index + 1}</p><h3 className="mt-8 font-display text-2xl">{title}</h3><p className="mt-4 text-sm leading-7 text-charcoal/62">{copy}</p></article>)}</div></section>
    <section className="border-y border-gold/20 bg-gold/10"><div className="mx-auto grid max-w-7xl gap-8 px-6 py-16 lg:grid-cols-[1fr_auto] lg:items-center lg:px-10"><div><p className="eyebrow text-burgundy/65">When you are ready</p><h2 className="mt-4 max-w-2xl font-display text-4xl leading-tight sm:text-5xl">See who could be waiting for the same kind of connection.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-charcoal/65">Membership unlocks complete profiles, interests, mutual matches, and private conversations. Plans and prices are shown clearly before payment.</p></div><Link to="/membership" className="rounded-full bg-burgundy px-6 py-3.5 text-center text-sm font-semibold text-cream">Explore membership</Link></div></section>
    <section className="mx-auto max-w-3xl px-6 py-20"><p className="eyebrow text-center text-burgundy/65">Good to know</p><h2 className="mt-4 text-center font-display text-4xl sm:text-5xl">A few quiet answers.</h2><div className="mt-10 space-y-3">{[["Is my profile public?", "Your profile is part of the member experience and visibility is controlled through your privacy settings."], ["Can people find me on Google?", "Private member areas are not intended for search indexing. Avoid sharing personal contact details in your profile."], ["Who can message me?", "Private chat is available after mutual interest and the relevant membership access is in place."], ["Can I leave whenever I want?", "You can manage your membership and request account deletion through account settings."]].map(([question, answer]) => <details key={question} className="group rounded-2xl border border-charcoal/10 bg-white/55 p-5"><summary className="cursor-pointer list-none pr-8 font-display text-xl">{question}<span className="float-right text-burgundy transition group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-7 text-charcoal/62">{answer}</p></details>)}</div></section>
    <section className="bg-burgundy text-cream"><div className="mx-auto max-w-7xl px-6 py-20 text-center lg:px-10"><p className="eyebrow text-gold">Take the first quiet step</p><h2 className="mx-auto mt-5 max-w-2xl font-display text-5xl leading-tight sm:text-6xl">Your next conversation could start here.</h2><Link to="/register" className="mt-8 inline-flex rounded-full bg-cream px-7 py-3.5 text-sm font-semibold text-burgundy transition hover:bg-white">Create my private profile</Link></div></section>
  </>;
}
