import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { api } from "../lib/api";
import { clientEnv } from "../env";
type Plan = { id: string; name: string; code: string; durationMonths: number; price: string; currency: string; description?: string | null; featured: boolean };
declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void }; } }
export default function MarketplaceMembership() { const [plans, setPlans] = useState<Plan[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [params] = useSearchParams(); const navigate = useNavigate(); const reason = params.get("reason");
  useEffect(() => { api<{ plans: Plan[] }>("/subscriptions/plans").then((data) => setPlans(data.plans)).catch((value) => setError(value instanceof Error ? value.message : "Plans are temporarily unavailable")); }, []);
  async function choose(plan: Plan) { setBusy(plan.id); setError(""); try { const order = await api<{ orderId: string; amount: number; currency: string }>("/payments/razorpay/order", { method: "POST", body: JSON.stringify({ planCode: plan.code }) }); const open = () => { if (!window.Razorpay) { setError("Secure checkout could not be loaded. Please refresh and try again."); setBusy(""); return; } new window.Razorpay({ key: clientEnv.VITE_RAZORPAY_KEY_ID, amount: order.amount, currency: order.currency, order_id: order.orderId, name: "Sshh... Koi Hai?", description: `${plan.name} membership`, handler: async (response: { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string }) => { try { await api("/payments/razorpay/verify", { method: "POST", body: JSON.stringify({ razorpayOrderId: response.razorpay_order_id, razorpayPaymentId: response.razorpay_payment_id, razorpaySignature: response.razorpay_signature }) }); navigate("/app/discover?membership=activated"); } catch (value) { setError(value instanceof Error ? value.message : "Payment verification failed"); } finally { setBusy(""); } }, ondismiss: () => setBusy("") }).open(); }; if (window.Razorpay) open(); else { const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.onload = open; script.onerror = () => { setBusy(""); setError("Secure checkout could not be loaded."); }; document.body.appendChild(script); } } catch (value) { setBusy(""); if (value instanceof Error && value.message.includes("Authentication")) navigate("/login"); else setError(value instanceof Error ? value.message : "Unable to start checkout"); } }
  return <section className="marketplace-shell min-h-[calc(100vh-72px)]"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-6 lg:px-10"><div className="mx-auto max-w-3xl text-center"><span className="trust-chip">Discovery is free · No hidden charges</span><h1 className="mt-5 font-display text-5xl sm:text-6xl">Connect when it feels right.</h1><p className="mt-5 text-base leading-8 text-charcoal/65">Membership unlocks deeper connections, unlimited interests and private conversations after mutual acceptance.</p></div>{reason && <div className="mx-auto mt-8 max-w-3xl rounded-2xl border border-gold/40 bg-gold/10 p-5 text-center"><p className="font-semibold text-burgundy">{reason === "chat" ? "A mutual connection is ready for a private conversation." : "Membership is needed to send interest."}</p><p className="mt-1 text-sm text-charcoal/60">Choose a plan below to continue.</p></div>}<div className="mx-auto mt-10 grid max-w-6xl gap-5 md:grid-cols-3">{!plans.length && !error && [1, 2, 3].map((item) => <div key={item} className="skeleton h-80 rounded-3xl" />)}{error && <p className="md:col-span-3 rounded-2xl bg-red-50 p-5 text-center text-sm text-red-800">{error}</p>}{plans.map((plan) => <article key={plan.id} className={`relative rounded-3xl border p-7 ${plan.featured ? "border-burgundy bg-burgundy text-cream shadow-soft" : "border-charcoal/10 bg-white"}`}>{plan.featured && <span className="absolute right-5 top-5 rounded-full bg-gold px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-plum">Best value</span>}<p className={`text-xs font-bold uppercase tracking-[.25em] ${plan.featured ? "text-gold" : "text-burgundy/60"}`}>{plan.name}</p><p className="mt-7 font-display text-5xl">{plan.currency} {Number(plan.price).toLocaleString("en-IN")}</p><p className={`mt-2 text-sm ${plan.featured ? "text-cream/65" : "text-charcoal/55"}`}>{plan.description || `${plan.durationMonths} month${plan.durationMonths > 1 ? "s" : ""} of member access`}</p><ul className={`mt-7 space-y-3 text-sm ${plan.featured ? "text-cream/80" : "text-charcoal/65"}`}><li>✓ Unlimited interests</li><li>✓ Private conversations</li><li>✓ Complete profiles and filters</li></ul><button onClick={() => void choose(plan)} disabled={Boolean(busy)} className={`mt-8 w-full rounded-full px-4 py-3 text-sm font-bold ${plan.featured ? "bg-cream text-burgundy" : "bg-burgundy text-cream"}`}>{busy === plan.id ? "Opening secure checkout…" : "Choose this plan"}</button></article>)}</div><p className="mx-auto mt-8 max-w-2xl text-center text-xs leading-5 text-charcoal/45">Secure checkout is handled by Razorpay. Your payment details are not stored on this website. Plans and billing terms are shown before payment.</p></div></section>;
}
