import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../lib/api";

type Match = { id: string; conversationId: string | null; profile: { id: string; displayName: string; age: number; city: string | null; profileImages: string[]; primaryImageIndex: number } };

export default function Matches() {
  const [matches, setMatches] = useState<Match[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); setError(""); try { const data = await api<{ matches: Match[] }>("/matches"); setMatches(data.matches); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load matches"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  return <section className="mx-auto max-w-6xl px-5 py-10 sm:px-6 sm:py-14 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-burgundy/65">Mutual connections</p><h1 className="mt-3 font-display text-4xl sm:text-5xl">The conversation can begin here.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-charcoal/60">These are the people who have chosen to connect with you too.</p></div><Link to="/app/discover" className="rounded-full border border-charcoal/15 px-4 py-2.5 text-sm font-semibold text-burgundy">Find people</Link></div>{error && <div role="alert" className="mt-8 rounded-2xl bg-red-50 p-5 text-sm text-red-800"><p>{error}</p><button onClick={() => void load()} className="mt-3 font-semibold underline">Try again</button></div>}{loading && <div className="mt-10 grid gap-5 md:grid-cols-2">{[1, 2].map((item) => <div key={item} className="skeleton h-40 rounded-3xl" />)}</div>}{!loading && !error && !matches.length && <div className="mt-10 rounded-3xl border border-charcoal/10 bg-white/60 p-10 text-center sm:p-12"><p className="font-display text-3xl">No matches yet.</p><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-charcoal/60">A match happens when interest meets interest. Keep exploring at your own pace.</p><Link to="/app/discover" className="mt-6 inline-flex rounded-full bg-burgundy px-5 py-3 text-sm font-semibold text-cream">Start discovering</Link></div>}{!loading && !error && matches.length > 0 && <div className="mt-10 grid gap-5 md:grid-cols-2">{matches.map((match) => { const image = match.profile.profileImages[match.profile.primaryImageIndex] ?? match.profile.profileImages[0]; return <article key={match.id} className="flex gap-5 rounded-3xl border border-charcoal/10 bg-white/70 p-5 shadow-sm"><Link to={`/app/profile/${match.profile.id}`} className="h-28 w-28 shrink-0 overflow-hidden rounded-2xl bg-gradient-to-br from-rose to-burgundy" aria-label={`View ${match.profile.displayName}'s profile`}>{image && <img src={image} alt="" className="h-full w-full object-cover" />}</Link><div className="min-w-0"><Link to={`/app/profile/${match.profile.id}`}><h2 className="font-display text-2xl hover:text-burgundy">{match.profile.displayName}, {match.profile.age}</h2></Link><p className="mt-1 text-sm text-charcoal/55">{match.profile.city ?? "Location private"}</p><p className="mt-3 text-xs font-semibold uppercase tracking-[0.2em] text-gold">Mutual interest</p><div className="mt-4 flex flex-wrap gap-2">{match.conversationId && <Link to={`/app/messages/${match.conversationId}`} className="rounded-full bg-burgundy px-4 py-2.5 text-xs font-semibold text-cream">Start private chat</Link>}<Link to={`/app/profile/${match.profile.id}`} className="rounded-full border border-charcoal/15 px-4 py-2.5 text-xs font-semibold text-burgundy">View profile</Link></div></div></article>; })}</div>}</section>;
}
