import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../lib/api";
import SafetyActions from "../components/SafetyActions";

type Profile = { id: string; displayName: string; age: number; gender?: string; city: string | null; bio: string | null; interests: string[]; profileImages: string[]; primaryImageIndex: number; lookingFor?: string | null; relationshipIntent?: string | null; occupation?: string | null; education?: string | null; languages?: string[] };

export default function MemberProfilePage() {
  const { userId } = useParams(); const [profile, setProfile] = useState<Profile | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [membershipPrompt, setMembershipPrompt] = useState(false); const [sending, setSending] = useState(false); const [sent, setSent] = useState(false);
  useEffect(() => { if (!userId) return; api<{ profile: Profile }>(`/profile/${userId}`).then((data) => setProfile(data.profile)).catch((e) => setError(e instanceof Error ? e.message : "This profile is not available")).finally(() => setLoading(false)); }, [userId]);
  async function sendInterest() { if (!profile || sending || sent) return; setSending(true); setError(""); try { await api("/interests", { method: "POST", body: JSON.stringify({ receiverId: profile.id }) }); setSent(true); } catch (e) { const message = e instanceof Error ? e.message : "Unable to send interest"; if (message.toLowerCase().includes("membership")) setMembershipPrompt(true); else setError(message); } finally { setSending(false); } }
  if (loading) return <section className="mx-auto max-w-5xl px-5 py-10 sm:px-6 sm:py-14"><div className="skeleton h-[28rem] rounded-3xl" /></section>;
  if (!profile) return <section className="mx-auto max-w-5xl px-5 py-16 text-center sm:px-6"><p className="font-display text-3xl">This profile is no longer available.</p><p className="mt-3 text-sm text-charcoal/60">It may be hidden or outside your current privacy settings.</p><Link to="/app/discover" className="mt-6 inline-flex rounded-full bg-burgundy px-5 py-3 text-sm font-semibold text-cream">Back to finding people</Link></section>;
  const image = profile.profileImages[profile.primaryImageIndex] ?? profile.profileImages[0];
  return <section className="mx-auto max-w-5xl px-5 py-8 sm:px-6 sm:py-14 lg:px-10"><Link to="/app/discover" className="text-sm font-semibold text-burgundy">← Back to finding people</Link>{membershipPrompt && <div className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-gold/30 bg-gold/10 p-5"><div><p className="font-semibold text-burgundy">Ready to connect privately?</p><p className="mt-1 text-sm text-charcoal/60">Subscribe to send unlimited interests and start private conversations.</p></div><Link to="/membership" className="rounded-full bg-burgundy px-5 py-3 text-sm font-semibold text-cream">Explore membership</Link></div>}{error && <p role="alert" className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-800">{error}</p>}<div className="mt-6 overflow-hidden rounded-3xl border border-charcoal/10 bg-white/75 shadow-soft"><div className="grid lg:grid-cols-[.9fr_1.1fr]"><div className="aspect-[4/3] bg-gradient-to-br from-rose via-burgundy to-plum lg:aspect-auto lg:min-h-[34rem]">{image && <img src={image} alt={`${profile.displayName}'s profile`} className="h-full w-full object-cover" />}</div><div className="p-6 sm:p-9"><p className="eyebrow text-burgundy/65">Member profile</p><h1 className="mt-4 font-display text-4xl sm:text-5xl">{profile.displayName}, {profile.age}</h1><p className="mt-3 text-sm text-charcoal/55">{profile.city ?? "Location private"}</p>{profile.relationshipIntent && <p className="mt-7 rounded-2xl bg-cream/70 p-4 text-sm font-semibold text-burgundy">{profile.relationshipIntent}</p>}<p className="mt-7 text-base leading-8 text-charcoal/70">{profile.bio || "This member is leaving room for a good conversation."}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button onClick={() => void sendInterest()} disabled={sending || sent} className="rounded-full bg-burgundy px-6 py-3 text-sm font-semibold text-cream disabled:opacity-50">{sending ? "Sending..." : sent ? "Interest sent" : "Send interest"}</button><SafetyActions userId={profile.id} displayName={profile.displayName} onBlocked={() => setProfile(null)} /></div><div className="mt-9 grid gap-5 border-t border-charcoal/10 pt-7 sm:grid-cols-2"><div><p className="eyebrow text-burgundy/60">Looking for</p><p className="mt-2 text-sm text-charcoal/70">{profile.lookingFor || "Open to discovery"}</p></div>{profile.occupation && <div><p className="eyebrow text-burgundy/60">About their day</p><p className="mt-2 text-sm text-charcoal/70">{profile.occupation}</p></div>}</div>{profile.interests.length > 0 && <div className="mt-7"><p className="eyebrow text-burgundy/60">Interests</p><div className="mt-3 flex flex-wrap gap-2">{profile.interests.map((interest) => <span key={interest} className="rounded-full bg-cream px-3 py-1.5 text-xs text-burgundy">{interest}</span>)}</div></div>}<p className="mt-8 text-xs leading-5 text-charcoal/45">Share only what you are comfortable sharing. You can block or report a member at any time.</p></div></div></div></section>;
}
