import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../lib/api";

type Notice = { id: string; title: string; body: string; readAt: string | null; createdAt: string };
type Preferences = Record<string, boolean>;
const labelFor = (key: string) => key.replace(/[A-Z]/g, (character) => ` ${character}`).replace(/^./, (character) => character.toUpperCase());

export default function Notifications() {
  const [items, setItems] = useState<Notice[]>([]); const [unread, setUnread] = useState(0); const [preferences, setPreferences] = useState<Preferences | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); setError(""); try { const [notifications, settings] = await Promise.all([api<{ notifications: Notice[]; unreadCount: number }>("/notifications?pageSize=50"), api<{ preferences: Preferences }>("/notifications/preferences")]); setItems(notifications.notifications); setUnread(notifications.unreadCount); setPreferences(settings.preferences); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load notifications"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function read(id: string) { const wasUnread = items.find((item) => item.id === id)?.readAt == null; try { await api(`/notifications/${id}/read`, { method: "PATCH" }); setItems((current) => current.map((item) => item.id === id ? { ...item, readAt: item.readAt ?? new Date().toISOString() } : item)); if (wasUnread) setUnread((current) => Math.max(0, current - 1)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update notification"); } }
  async function readAll() { if (saving || unread === 0) return; setSaving(true); try { await api("/notifications/read-all", { method: "POST" }); setItems((current) => current.map((item) => ({ ...item, readAt: item.readAt ?? new Date().toISOString() }))); setUnread(0); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update notifications"); } finally { setSaving(false); } }
  async function save(next: Preferences) { setPreferences(next); setSaving(true); setError(""); try { await api("/notifications/preferences", { method: "PUT", body: JSON.stringify(next) }); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save notification preferences"); } finally { setSaving(false); } }
  return <section className="mx-auto max-w-4xl px-5 py-10 sm:px-6 sm:py-12"><Link to="/account" className="text-sm font-semibold text-burgundy">Back to your space</Link><div className="mt-5 grid gap-6 lg:grid-cols-[1fr_280px]"><div className="rounded-3xl border border-charcoal/10 bg-white/80 p-5 shadow-soft sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow text-burgundy/65">Your updates</p><h1 className="mt-2 font-display text-3xl">Notifications</h1></div><button disabled={!unread} className="text-sm font-semibold text-burgundy disabled:opacity-40" onClick={() => void readAll()}>Mark all read{unread ? ` (${unread})` : ""}</button></div>{error && <div role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800"><p>{error}</p><button onClick={() => void load()} className="mt-2 font-semibold underline">Try again</button></div>}{loading && <div className="mt-6 space-y-3">{[1, 2, 3].map((item) => <div key={item} className="skeleton h-20 rounded-2xl" />)}</div>}{!loading && !error && !items.length && <div className="mt-8 rounded-2xl border border-charcoal/10 bg-cream/50 p-8 text-center"><p className="font-display text-2xl">Your space is quiet for now.</p><p className="mt-2 text-sm leading-6 text-charcoal/60">When someone shows interest or a match is ready, you will see it here.</p><Link to="/app/discover" className="mt-5 inline-flex rounded-full bg-burgundy px-4 py-2.5 text-sm font-semibold text-cream">Find people</Link></div>}{!loading && <div className="mt-6 space-y-2">{items.map((item) => <button key={item.id} onClick={() => void read(item.id)} className={`block min-h-[76px] w-full rounded-2xl border p-4 text-left transition ${item.readAt ? "border-charcoal/10 opacity-60" : "border-burgundy/20 bg-cream/60"}`}><div className="flex justify-between gap-3"><strong className="text-sm">{item.title}</strong><time className="shrink-0 text-xs text-charcoal/50">{new Date(item.createdAt).toLocaleDateString()}</time></div><p className="mt-1 text-sm leading-6 text-charcoal/65">{item.body}</p></button>)}</div>}</div><div className="rounded-3xl border border-charcoal/10 bg-white/80 p-5 shadow-soft sm:p-6"><h2 className="font-display text-2xl">Notification privacy</h2><p className="mt-2 text-sm leading-6 text-charcoal/60">Choose which updates you receive. Chat stays inside the platform.</p>{preferences && <div className="mt-5 space-y-4 text-sm">{Object.entries(preferences).map(([key, value]) => <label key={key} className="flex items-center justify-between gap-3"><span>{labelFor(key)}</span><input type="checkbox" checked={value} disabled={saving} onChange={(event) => void save({ ...preferences, [key]: event.target.checked })} className="h-5 w-5 accent-burgundy" /></label>)}</div>}</div></div></section>;
}
