import { useEffect, useState } from "react";
import { api } from "../lib/api";

type Privacy = { visibility: "VISIBLE" | "HIDDEN"; showOnlineStatus: boolean; showCity: boolean };
const rowClass = "flex items-start justify-between gap-5 rounded-2xl border border-charcoal/10 bg-cream/40 p-4";

export default function PrivacySettingsPage() {
  const [privacy, setPrivacy] = useState<Privacy | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { api<{ privacy: Privacy }>("/settings/privacy").then((data) => setPrivacy(data.privacy)).catch((e) => setError(e instanceof Error ? e.message : "Unable to load privacy settings")); }, []);
  async function save() { if (!privacy) return; setSaving(true); setError(""); setMessage(""); try { await api("/settings/privacy", { method: "PUT", body: JSON.stringify(privacy) }); setMessage("Your privacy settings have been saved."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save privacy settings"); } finally { setSaving(false); } }
  if (!privacy) return <div className="rounded-3xl bg-white/80 p-6 shadow-soft"><h2 className="font-display text-2xl">Privacy</h2>{error ? <div className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800"><p>{error}</p><button onClick={() => window.location.reload()} className="mt-2 font-semibold underline">Try again</button></div> : <div className="skeleton mt-5 h-40 rounded-2xl" />}</div>;
  return <div className="rounded-3xl bg-white/80 p-6 shadow-soft"><div><h2 className="font-display text-2xl">Privacy</h2><p className="mt-2 text-sm leading-6 text-charcoal/60">Choose what other members can see. These controls apply to your member profile.</p></div>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{error}</p>}{message && <p role="status" className="mt-5 rounded-xl bg-green-50 p-4 text-sm text-green-800">{message}</p>}<div className="mt-6 space-y-3"><label className={rowClass}><span><span className="block text-sm font-semibold">Profile visibility</span><span className="mt-1 block text-xs leading-5 text-charcoal/55">Hidden profiles do not appear in discovery.</span></span><select aria-label="Profile visibility" className="rounded-xl border border-charcoal/15 bg-cream px-3 py-2 text-sm" value={privacy.visibility} onChange={(event) => setPrivacy({ ...privacy, visibility: event.target.value as Privacy["visibility"] })}><option value="VISIBLE">Visible</option><option value="HIDDEN">Hidden</option></select></label><label className={rowClass}><span><span className="block text-sm font-semibold">Show online status</span><span className="mt-1 block text-xs leading-5 text-charcoal/55">Let members know when you are currently active.</span></span><input aria-label="Show online status" type="checkbox" checked={privacy.showOnlineStatus} onChange={(event) => setPrivacy({ ...privacy, showOnlineStatus: event.target.checked })} className="mt-1 h-5 w-5 accent-burgundy" /></label><label className={rowClass}><span><span className="block text-sm font-semibold">Show my city</span><span className="mt-1 block text-xs leading-5 text-charcoal/55">Show your city on your member profile, never your exact address.</span></span><input aria-label="Show city" type="checkbox" checked={privacy.showCity} onChange={(event) => setPrivacy({ ...privacy, showCity: event.target.checked })} className="mt-1 h-5 w-5 accent-burgundy" /></label></div><button onClick={() => void save()} disabled={saving} className="mt-6 rounded-full bg-burgundy px-5 py-3 text-sm font-semibold text-cream disabled:opacity-50">{saving ? "Saving..." : "Save privacy settings"}</button></div>;
}
