import { useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { api } from "../lib/api";

type FormState = { dateOfBirth: string; displayName: string; gender: string; maritalStatus: string; lookingFor: string; city: string; email: string; password: string; confirmPassword: string; confirmedAdult: boolean; acceptedTerms: boolean };
const initialForm: FormState = { dateOfBirth: "", displayName: "", gender: "", maritalStatus: "SINGLE", lookingFor: "CHAT", city: "", email: "", password: "", confirmPassword: "", confirmedAdult: false, acceptedTerms: false };
const input = "profile-input mt-2";

function Select({ label, name, value, onChange, children }: { label: string; name: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) {
  return <label className="block text-sm text-charcoal/75">{label}<select name={name} value={value} onChange={(event) => onChange(event.target.value)} className={input} required>{children}</select></label>;
}

export default function ProgressiveRegister() {
  const [step, setStep] = useState(1); const [form, setForm] = useState(initialForm); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const update = (key: keyof FormState, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  function next(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (step === 1 && !form.confirmedAdult) { setError("Please confirm that you are 18 or older to continue."); return; } if (step < 4) { setStep((current) => current + 1); return; } void submit(); }
  async function submit() { if (form.password.length < 10) { setError("Password must be at least 10 characters."); return; } if (form.password !== form.confirmPassword) { setError("Passwords do not match."); return; } if (!form.acceptedTerms) { setError("Please accept the terms and privacy policy to continue."); return; } setBusy(true); try { await api("/auth/register", { method: "POST", body: JSON.stringify(form) }); setMessage("Your private account is ready. Check your email to verify it before signing in."); setForm(initialForm); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create your account"); } finally { setBusy(false); } }
  const titles = ["A quiet place starts with 18+", "How should we know you?", "What kind of connection feels right?", "Create your private account"];
  return <section className="mx-auto max-w-xl px-5 py-8 sm:px-6 sm:py-14"><div className="rounded-[2rem] border border-burgundy/10 bg-white/85 p-6 shadow-soft sm:p-10"><p className="text-xs uppercase tracking-[0.3em] text-burgundy/65">Sshh... Koi Hai?</p><div className="mt-6 flex items-center justify-between gap-4"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-charcoal/50">Step {step} of 4</p><p className="text-xs text-charcoal/50">{step === 4 ? "Almost there" : "Takes about 2 minutes"}</p></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-charcoal/10"><div className="h-full rounded-full bg-gold transition-all" style={{ width: `${step * 25}%` }} /></div><h1 className="mt-7 font-display text-4xl leading-tight">{titles[step - 1]}</h1><p className="mt-3 text-sm leading-6 text-charcoal/60">{step === 1 ? "This is an adults-only private space. Your date of birth is used for age validation and is not shown publicly." : step === 2 ? "Use a name you are comfortable being known by. You can shape the rest of your profile later." : step === 3 ? "Your answers help us show more relevant people without making you search through noise." : "Your email is used for verification and account security. It is never shown publicly."}</p><form onSubmit={next} className="mt-7 space-y-5">
    {step === 1 && <><label className="block text-sm text-charcoal/75">Date of birth<input type="date" value={form.dateOfBirth} onChange={(event) => update("dateOfBirth", event.target.value)} className={input} required /></label><label className="flex gap-3 text-sm leading-6 text-charcoal/70"><input type="checkbox" checked={form.confirmedAdult} onChange={(event) => update("confirmedAdult", event.target.checked)} className="mt-1 accent-burgundy" />I confirm that I am 18 or older.</label></>}
    {step === 2 && <><label className="block text-sm text-charcoal/75">First name or display name<input value={form.displayName} onChange={(event) => update("displayName", event.target.value)} placeholder="What should people call you?" className={input} minLength={2} maxLength={80} required /></label><Select label="How do you identify?" name="gender" value={form.gender} onChange={(value) => update("gender", value)}><option value="">Choose one</option><option value="MALE">Man</option><option value="FEMALE">Woman</option><option value="NON_BINARY">Non-binary</option><option value="OTHER">Prefer to self-describe</option><option value="PREFER_NOT_TO_SAY">Prefer not to say</option></Select><Select label="Relationship status" name="maritalStatus" value={form.maritalStatus} onChange={(value) => update("maritalStatus", value)}><option value="SINGLE">Single</option><option value="MARRIED">Married</option><option value="SEPARATED">Separated</option><option value="DIVORCED">Divorced</option><option value="WIDOWED">Widowed</option><option value="PREFER_NOT_TO_SAY">Prefer not to say</option></Select></>}
    {step === 3 && <><Select label="What are you looking for?" name="lookingFor" value={form.lookingFor} onChange={(value) => update("lookingFor", value)}><option value="CHAT">Private conversation</option><option value="FRIENDSHIP">Friendship</option><option value="DATING">Dating</option><option value="RELATIONSHIP">An emotional connection</option><option value="MARRIAGE">A long-term relationship</option></Select><label className="block text-sm text-charcoal/75">City or region<input value={form.city} onChange={(event) => update("city", event.target.value)} placeholder="Where are you based?" className={input} minLength={2} maxLength={100} required /></label><p className="rounded-2xl bg-cream/70 px-4 py-3 text-xs leading-5 text-charcoal/55">You can control whether your city is shown after joining.</p></>}
    {step === 4 && <><label className="block text-sm text-charcoal/75">Email<input type="email" autoComplete="email" value={form.email} onChange={(event) => update("email", event.target.value)} className={input} required /></label><label className="block text-sm text-charcoal/75">Password<input type="password" autoComplete="new-password" value={form.password} onChange={(event) => update("password", event.target.value)} className={input} minLength={10} required /></label><label className="block text-sm text-charcoal/75">Confirm password<input type="password" autoComplete="new-password" value={form.confirmPassword} onChange={(event) => update("confirmPassword", event.target.value)} className={input} minLength={10} required /></label><label className="flex gap-3 text-sm leading-6 text-charcoal/70"><input type="checkbox" checked={form.acceptedTerms} onChange={(event) => update("acceptedTerms", event.target.checked)} className="mt-1 accent-burgundy" />I accept the <Link to="/terms" className="text-burgundy underline">terms</Link> and <Link to="/privacy" className="text-burgundy underline">privacy policy</Link>.</label></>}
    {error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p>}{message && <p role="status" className="rounded-xl bg-green-50 px-4 py-3 text-sm text-green-800">{message}</p>}<div className="flex gap-3"><button type="button" onClick={() => { setError(""); setStep((current) => Math.max(1, current - 1)); }} disabled={step === 1 || busy} className="rounded-full border border-charcoal/15 px-5 py-3 text-sm font-semibold text-charcoal disabled:invisible">Back</button><button disabled={busy || Boolean(message)} className="flex-1 rounded-full bg-burgundy px-5 py-3 text-sm font-semibold text-cream disabled:opacity-50">{busy ? "Creating your account..." : step === 4 ? "Create private account" : "Continue"}</button></div></form><p className="mt-7 border-t border-charcoal/10 pt-5 text-sm text-charcoal/65">Already have an account? <Link className="text-burgundy underline" to="/login">Sign in</Link></p></div></section>;
}
