import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../lib/api";
type Account = { email: string; displayName: string };
type Privacy = { visibility: "VISIBLE" | "HIDDEN"; showOnlineStatus: boolean; showCity: boolean };
type Session = { id: string; createdAt: string; expiresAt: string };
type Membership = { subscription: { plan: { name: string }; startDate: string | null; endDate: string | null } | null };
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-3xl bg-white/80 p-6 shadow-soft"><h2 className="font-display text-2xl">{title}</h2>{children}</div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm">{label}<input className="profile-input" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
export function AccountSettings() { const [account, setAccount] = useState<Account | null>(null); const [name, setName] = useState(""); const [message, setMessage] = useState(""); const navigate = useNavigate(); useEffect(() => { api<{ account: Account }>("/settings/account").then((r) => { setAccount(r.account); setName(r.account.displayName); }); }, []); async function save() { await api("/settings/account", { method: "PUT", body: JSON.stringify({ displayName: name }) }); setMessage("Account details updated."); } async function remove() { if (window.prompt("Type DELETE to permanently delete your account") === "DELETE") { await api("/profile/me", { method: "DELETE", body: JSON.stringify({ confirmation: "DELETE" }) }); navigate("/"); } } return <Panel title="Account"><div className="mt-5 space-y-4"><Field label="Email" value={account?.email ?? "Loading..."} onChange={() => undefined} /><Field label="Display name" value={name} onChange={setName} /><button className="rounded-full bg-burgundy px-5 py-3 text-sm text-cream" onClick={save}>Save changes</button>{message && <p className="text-sm text-green-700">{message}</p>}<div className="border-t border-charcoal/10 pt-5"><h3 className="font-semibold text-red-800">Delete account</h3><p className="mt-2 text-sm text-charcoal/60">Your profile will be hidden and sessions revoked.</p><button className="mt-3 rounded-full border border-red-700/30 px-4 py-2 text-sm text-red-700" onClick={remove}>Delete account</button></div></div></Panel>; }
export function PrivacySettings() { const [privacy, setPrivacy] = useState<Privacy | null>(null); const [message, setMessage] = useState(""); useEffect(() => { api<{ privacy: Privacy }>("/settings/privacy").then((r) => setPrivacy(r.privacy)); }, []); if (!privacy) return <Panel title="Privacy">Loading...</Panel>; async function save() { await api("/settings/privacy", { method: "PUT", body: JSON.stringify(privacy) }); setMessage("Privacy settings updated."); } return <Panel title="Privacy"><div className="mt-5 space-y-4"><label className="flex items-center justify-between text-sm">Profile visibility<select className="rounded-xl border p-2" value={privacy.visibility} onChange={(e) => setPrivacy({ ...privacy, visibility: e.target.value as Privacy["visibility"] })}><option value="VISIBLE">VISIBLE</option><option value="HIDDEN">HIDDEN</option></select></label>{([ ["showOnlineStatus", "Show online status"], ["showCity", "Show city"] ] as const).map(([key, label]) => <label key={key} className="flex items-center justify-between text-sm">{label}<input type="checkbox" checked={privacy[key]} onChange={(e) => setPrivacy({ ...privacy, [key]: e.target.checked })} /></label>)}<button className="rounded-full bg-burgundy px-5 py-3 text-sm text-cream" onClick={save}>Save privacy</button>{message && <p className="text-sm text-green-700">{message}</p>}</div></Panel>; }
export function SecuritySettings() { const [form, setForm] = useState({ currentPassword: "", password: "", confirmPassword: "" }); const [sessions, setSessions] = useState<Session[]>([]); const navigate = useNavigate(); useEffect(() => { api<{ sessions: Session[] }>("/settings/security/sessions").then((r) => setSessions(r.sessions)); }, []); async function change() { await api("/auth/change-password", { method: "POST", body: JSON.stringify(form) }); navigate("/login"); } async function logoutAll() { await api("/auth/logout-all", { method: "POST" }); navigate("/login"); } return <Panel title="Security"><div className="mt-5 space-y-3"><Field label="Current password" value={form.currentPassword} onChange={(v) => setForm({ ...form, currentPassword: v })} /><Field label="New password" value={form.password} onChange={(v) => setForm({ ...form, password: v })} /><Field label="Confirm new password" value={form.confirmPassword} onChange={(v) => setForm({ ...form, confirmPassword: v })} /><button className="rounded-full bg-burgundy px-5 py-3 text-sm text-cream" onClick={change}>Change password</button><div className="border-t border-charcoal/10 pt-5"><h3 className="font-semibold">Active sessions</h3><p className="mt-2 text-sm text-charcoal/60">{sessions.length} active session(s).</p><button className="mt-3 rounded-full border border-burgundy/30 px-4 py-2 text-sm text-burgundy" onClick={logoutAll}>Log out all sessions</button></div></div></Panel>; }
export function MembershipSettings() { const [data, setData] = useState<Membership | null>(null); useEffect(() => { api<Membership>("/subscriptions/current").then(setData); }, []); return <Panel title="Membership"><div className="mt-5 space-y-3 text-sm">{data?.subscription ? <><p className="font-semibold text-burgundy">{data.subscription.plan.name}</p><p>Start: {data.subscription.startDate ? new Date(data.subscription.startDate).toLocaleDateString() : "-"}</p><p>Expiry: {data.subscription.endDate ? new Date(data.subscription.endDate).toLocaleDateString() : "-"}</p></> : <p className="text-charcoal/60">No active membership.</p>}<Link className="inline-block rounded-full bg-burgundy px-5 py-3 text-sm text-cream" to="/membership">Renew membership</Link></div></Panel>; }
