import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../lib/api";

type Account = { email: string; displayName: string };
type Privacy = { visibility: "VISIBLE" | "HIDDEN"; showOnlineStatus: boolean; showCity: boolean };
type Session = { id: string; createdAt: string; expiresAt: string };
type Membership = { subscription: { plan: { name: string }; startDate: string | null; endDate: string | null } | null };

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-3xl border border-charcoal/10 bg-white/80 p-6 shadow-soft sm:p-7"><h2 className="font-display text-2xl">{title}</h2>{children}</div>; }
function Field({ label, value, onChange, type = "text", readOnly = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; readOnly?: boolean }) { return <label className="block text-sm text-charcoal/75">{label}<input type={type} readOnly={readOnly} aria-readonly={readOnly || undefined} autoComplete={type === "password" ? (label.toLowerCase().includes("new") ? "new-password" : "current-password") : undefined} className={`profile-input ${readOnly ? "cursor-not-allowed bg-charcoal/[0.03] text-charcoal/55" : ""}`} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function Feedback({ error, message, retry }: { error?: string; message?: string; retry?: () => void }) { return <>{error && <div role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-800"><p>{error}</p>{retry && <button type="button" onClick={retry} className="mt-2 font-semibold underline">Try again</button>}</div>}{message && <p role="status" className="mt-4 rounded-xl bg-green-50 p-4 text-sm text-green-800">{message}</p>}</>; }

export function AccountSettings() {
  const [account, setAccount] = useState<Account | null>(null); const [name, setName] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [removing, setRemoving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const navigate = useNavigate();
  async function load() { setLoading(true); setError(""); try { const result = await api<{ account: Account }>("/settings/account"); setAccount(result.account); setName(result.account.displayName); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load account settings"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function save() { setBusy(true); setError(""); setMessage(""); try { await api("/settings/account", { method: "PUT", body: JSON.stringify({ displayName: name }) }); setMessage("Account details updated."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update account details"); } finally { setBusy(false); } }
  async function remove() { if (window.prompt("Type DELETE to permanently delete your account") !== "DELETE") return; setRemoving(true); setError(""); try { await api("/profile/me", { method: "DELETE", body: JSON.stringify({ confirmation: "DELETE" }) }); navigate("/"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete your account"); setRemoving(false); } }
  return <Panel title="Account"><div className="mt-5 space-y-4">{loading ? <div className="skeleton h-28 rounded-2xl" /> : <><Field label="Email" value={account?.email ?? ""} onChange={() => undefined} readOnly /><p className="-mt-2 text-xs leading-5 text-charcoal/50">Your email is used for sign-in and verification. It cannot be changed here.</p><Field label="Display name" value={name} onChange={setName} /><button type="button" disabled={busy || !name.trim()} className="rounded-full bg-burgundy px-5 py-3 text-sm font-semibold text-cream disabled:opacity-50" onClick={() => void save()}>{busy ? "Saving..." : "Save changes"}</button></>}{!loading && <div className="border-t border-charcoal/10 pt-5"><h3 className="font-semibold text-red-800">Delete account</h3><p className="mt-2 text-sm leading-6 text-charcoal/60">Your profile will be hidden and sessions revoked. This cannot be undone.</p><button type="button" disabled={removing} className="mt-3 rounded-full border border-red-700/30 px-4 py-2 text-sm text-red-700 disabled:opacity-50" onClick={() => void remove()}>{removing ? "Deleting..." : "Delete account"}</button></div>}<Feedback error={error} message={message} retry={!loading ? () => void load() : undefined} /></div></Panel>;
}

export function PrivacySettings() {
  const [privacy, setPrivacy] = useState<Privacy | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { setLoading(true); setError(""); try { const result = await api<{ privacy: Privacy }>("/settings/privacy"); setPrivacy(result.privacy); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load privacy settings"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function save() { if (!privacy) return; setSaving(true); setError(""); setMessage(""); try { await api("/settings/privacy", { method: "PUT", body: JSON.stringify(privacy) }); setMessage("Privacy settings updated."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save privacy settings"); } finally { setSaving(false); } }
  return <Panel title="Privacy">{loading ? <div className="mt-5 skeleton h-48 rounded-2xl" /> : error && !privacy ? <Feedback error={error} retry={() => void load()} /> : privacy && <><p className="mt-2 text-sm leading-6 text-charcoal/60">Choose what other members can see. These controls apply to your member profile.</p><div className="mt-5 space-y-4"><label className="flex items-center justify-between gap-4 text-sm"><span><span className="font-semibold">Profile visibility</span><span className="mt-1 block text-xs text-charcoal/55">Hidden profiles do not appear in discovery.</span></span><select aria-label="Profile visibility" className="rounded-xl border border-charcoal/15 bg-cream px-3 py-2" value={privacy.visibility} onChange={(e) => setPrivacy({ ...privacy, visibility: e.target.value as Privacy["visibility"] })}><option value="VISIBLE">Visible</option><option value="HIDDEN">Hidden</option></select></label>{([ ["showOnlineStatus", "Show online status", "Let members know when you are currently active."], ["showCity", "Show my city", "Show your city, never your exact address."] ] as const).map(([key, label, description]) => <label key={key} className="flex items-center justify-between gap-4 text-sm"><span><span className="font-semibold">{label}</span><span className="mt-1 block text-xs text-charcoal/55">{description}</span></span><input aria-label={label} type="checkbox" checked={privacy[key]} onChange={(e) => setPrivacy({ ...privacy, [key]: e.target.checked })} className="h-5 w-5 accent-burgundy" /></label>)}</div><button type="button" disabled={saving} className="mt-6 rounded-full bg-burgundy px-5 py-3 text-sm font-semibold text-cream disabled:opacity-50" onClick={() => void save()}>{saving ? "Saving..." : "Save privacy settings"}</button><Feedback error={error} message={message} /></>}</Panel>;
}

export function SecuritySettings() {
  const [form, setForm] = useState({ currentPassword: "", password: "", confirmPassword: "" }); const [sessions, setSessions] = useState<Session[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const navigate = useNavigate();
  async function load() { setLoading(true); setError(""); try { const result = await api<{ sessions: Session[] }>("/settings/security/sessions"); setSessions(result.sessions); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load security settings"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function change() { setError(""); if (form.password.length < 10) { setError("New password must be at least 10 characters."); return; } if (form.password !== form.confirmPassword) { setError("Passwords do not match."); return; } setBusy(true); try { await api("/auth/change-password", { method: "POST", body: JSON.stringify(form) }); navigate("/login"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to change password"); } finally { setBusy(false); } }
  async function logoutAll() { setBusy(true); setError(""); try { await api("/auth/logout-all", { method: "POST" }); navigate("/login"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to log out sessions"); setBusy(false); } }
  return <Panel title="Security"><p className="mt-2 text-sm leading-6 text-charcoal/60">Keep your account protected with a strong password and review active sessions.</p>{!loading && <div className="mt-5 space-y-3"><Field label="Current password" value={form.currentPassword} onChange={(v) => setForm({ ...form, currentPassword: v })} type="password" /><Field label="New password" value={form.password} onChange={(v) => setForm({ ...form, password: v })} type="password" /><Field label="Confirm new password" value={form.confirmPassword} onChange={(v) => setForm({ ...form, confirmPassword: v })} type="password" /><button type="button" disabled={busy} className="rounded-full bg-burgundy px-5 py-3 text-sm font-semibold text-cream disabled:opacity-50" onClick={() => void change()}>{busy ? "Updating..." : "Change password"}</button><div className="border-t border-charcoal/10 pt-5"><h3 className="font-semibold">Active sessions</h3><p className="mt-2 text-sm text-charcoal/60">{sessions.length} active session{sessions.length === 1 ? "" : "s"}.</p><button type="button" disabled={busy} className="mt-3 rounded-full border border-burgundy/30 px-4 py-2 text-sm font-semibold text-burgundy disabled:opacity-50" onClick={() => void logoutAll()}>Log out all sessions</button></div></div>}{loading && <div className="mt-5 skeleton h-56 rounded-2xl" />}<Feedback error={error} retry={!loading ? () => void load() : undefined} /></Panel>;
}

export function MembershipSettings() {
  const [data, setData] = useState<Membership | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { setData(await api<Membership>("/subscriptions/current")); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load membership status"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  return <Panel title="Membership">{loading ? <div className="mt-5 skeleton h-32 rounded-2xl" /> : error ? <Feedback error={error} retry={() => void load()} /> : <div className="mt-5 space-y-3 text-sm">{data?.subscription ? <><p className="font-semibold text-burgundy">{data.subscription.plan.name}</p><p>Started: {data.subscription.startDate ? new Date(data.subscription.startDate).toLocaleDateString() : "-"}</p><p>Expires: {data.subscription.endDate ? new Date(data.subscription.endDate).toLocaleDateString() : "-"}</p></> : <p className="text-charcoal/60">No active membership.</p>}<Link className="inline-block rounded-full bg-burgundy px-5 py-3 text-sm font-semibold text-cream" to="/membership">{data?.subscription ? "View membership options" : "Explore membership"}</Link></div>}</Panel>;
}
