import { Router } from "express";
import type { Prisma } from "@prisma/client";
import { z } from "zod";
import { prisma } from "../db/prisma.js";
import { requireMembership } from "../lib/membership.js";
import { AppError } from "../lib/appError.js";
import { sendSuccess } from "../lib/apiResponse.js";
import { createMatchWithConversation } from "../lib/matching.js";
import { publicProfile } from "../lib/profile.js";
import { createNotification } from "../lib/notifications.js";

const router = Router();
const interestInclude = { receiver: { include: { profile: true } }, sender: { include: { profile: true } } } as const;
type InterestWithPeople = Prisma.InterestGetPayload<{ include: typeof interestInclude }>;

router.post("/", requireMembership, async (req, res, next) => { try { const input = z.object({ receiverId: z.string().min(1), note: z.string().trim().max(500).optional() }).parse(req.body); const senderId = req.authUser!.id; if (senderId === input.receiverId) throw new AppError("You cannot send interest to yourself", 400, "SELF_INTEREST"); const target = await prisma.user.findUnique({ where: { id: input.receiverId }, include: { profile: true } }); if (!target || target.status !== "ACTIVE" || !target.isEmailVerified || !target.profile || target.profile.visibility !== "VISIBLE") throw new AppError("This member is unavailable", 404, "MEMBER_NOT_FOUND"); const blocked = await prisma.block.findFirst({ where: { OR: [{ blockerId: senderId, blockedUserId: input.receiverId }, { blockerId: input.receiverId, blockedUserId: senderId }] } }); if (blocked) throw new AppError("Interest cannot be sent to this member", 403, "BLOCKED_MEMBER"); const existing = await prisma.interest.findUnique({ where: { senderId_receiverId: { senderId, receiverId: input.receiverId } } }); if (existing) throw new AppError("You have already interacted with this member", 409, "INTEREST_EXISTS"); const interest = await prisma.interest.create({ data: { senderId, receiverId: input.receiverId, ...(input.note !== undefined ? { note: input.note } : {}) }, include: interestInclude }); await createNotification(input.receiverId, "INTEREST_RECEIVED", "New interest", `${req.authUser!.displayName} sent you an interest.`); return sendSuccess(res, { interest: serializeInterest(interest, "sent") }, 201); } catch (error) { return next(error); } });

router.delete("/", requireMembership, async (req, res, next) => { try { const { interestId } = z.object({ interestId: z.string().min(1) }).parse(req.body); const interest = await prisma.interest.findFirst({ where: { id: interestId, senderId: req.authUser!.id, status: "PENDING" } }); if (!interest) throw new AppError("Pending interest not found", 404, "INTEREST_NOT_FOUND"); await prisma.interest.update({ where: { id: interest.id }, data: { status: "CANCELLED", respondedAt: new Date() } }); return sendSuccess(res, { withdrawn: true }); } catch (error) { return next(error); } });

router.get("/sent", requireMembership, async (req, res, next) => { try { const interests = await prisma.interest.findMany({ where: { senderId: req.authUser!.id }, include: interestInclude, orderBy: { createdAt: "desc" } }); return sendSuccess(res, { interests: interests.map((interest) => serializeInterest(interest, "sent")) }); } catch (error) { return next(error); } });
router.get("/received", requireMembership, async (req, res, next) => { try { const interests = await prisma.interest.findMany({ where: { receiverId: req.authUser!.id }, include: interestInclude, orderBy: { createdAt: "desc" } }); return sendSuccess(res, { interests: interests.map((interest) => serializeInterest(interest, "received")) }); } catch (error) { return next(error); } });

router.post("/:interestId/accept", requireMembership, async (req, res, next) => { try { const interestId = req.params.interestId; if (!interestId) throw new AppError("Interest not found", 404, "INTEREST_NOT_FOUND"); const interest = await prisma.interest.findFirst({ where: { id: interestId, receiverId: req.authUser!.id, status: "PENDING" } }); if (!interest) throw new AppError("Pending interest not found", 404, "INTEREST_NOT_FOUND"); const reverse = await prisma.interest.findUnique({ where: { senderId_receiverId: { senderId: interest.receiverId, receiverId: interest.senderId } } }); const result = await prisma.$transaction(async (tx) => { await tx.interest.update({ where: { id: interest.id }, data: { status: "ACCEPTED", respondedAt: new Date() } }); if (reverse?.status === "PENDING") await tx.interest.update({ where: { id: reverse.id }, data: { status: "ACCEPTED", respondedAt: new Date() } }); return createMatchWithConversation(interest.senderId, interest.receiverId, tx); }); await Promise.all([createNotification(interest.senderId, "INTEREST_ACCEPTED", "Interest accepted", `${req.authUser!.displayName} accepted your interest.`), createNotification(interest.senderId, "NEW_MATCH", "New match", `You and ${req.authUser!.displayName} can now start a private conversation.`), createNotification(interest.receiverId, "NEW_MATCH", "New match", `You and ${interest.senderId === req.authUser!.id ? "your new match" : "this member"} can now start a private conversation.`)]); return sendSuccess(res, { accepted: true, matchId: result.match.id, conversationId: result.conversation.id }); } catch (error) { return next(error); } });

router.post("/:interestId/reject", requireMembership, async (req, res, next) => { try { const interestId = req.params.interestId; if (!interestId) throw new AppError("Interest not found", 404, "INTEREST_NOT_FOUND"); const interest = await prisma.interest.findFirst({ where: { id: interestId, receiverId: req.authUser!.id, status: "PENDING" } }); if (!interest) throw new AppError("Pending interest not found", 404, "INTEREST_NOT_FOUND"); await prisma.interest.update({ where: { id: interest.id }, data: { status: "REJECTED", respondedAt: new Date() } }); return sendSuccess(res, { rejected: true }); } catch (error) { return next(error); } });

function serializeInterest(interest: InterestWithPeople, direction: "sent" | "received") { const person = direction === "sent" ? interest.receiver : interest.sender; return { id: interest.id, status: interest.status, note: interest.note, createdAt: interest.createdAt, respondedAt: interest.respondedAt, profile: person.profile ? publicProfile(person, person.profile) : null }; }
export default router;
