import "dotenv/config";
import crypto from "node:crypto";
import bcrypt from "bcryptjs";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { databaseUrl } from "../src/config/env.js";

const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: databaseUrl }) });
const TERMS_VERSION = "2026-08-31";
const demoPassword = process.env.DEMO_INITIAL_PASSWORD || `Demo-${cryptoRandom()}-Only!`;

function cryptoRandom() {
  return crypto.randomBytes(6).toString("hex");
}

function dob(yearsAgo: number, month: number, day: number) {
  return new Date(Date.UTC(new Date().getUTCFullYear() - yearsAgo, month - 1, day));
}

const demoUsers = [
  { key: "aanya", email: "aanya.demo@example.test", displayName: "Aanya Mehta", gender: "FEMALE" as const, city: "Mumbai", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 28, interests: ["Cinema", "Travel", "Cooking"], bio: "Slow mornings, good films, and conversations with a little depth.", occupation: "Architect", education: "Design", languages: ["English", "Hindi"], relationshipIntent: "A thoughtful connection", onlineStatus: true },
  { key: "kabir", email: "kabir.demo@example.test", displayName: "Kabir Rao", gender: "MALE" as const, city: "Delhi", maritalStatus: "SINGLE" as const, lookingFor: "RELATIONSHIP" as const, age: 31, interests: ["Jazz", "Books", "Running"], bio: "Collecting records, city walks, and stories worth staying up for.", occupation: "Product designer", education: "Communication", languages: ["English", "Hindi"], relationshipIntent: "A genuine relationship", onlineStatus: false },
  { key: "meera", email: "meera.demo@example.test", displayName: "Meera Iyer", gender: "FEMALE" as const, city: "Bengaluru", maritalStatus: "DIVORCED" as const, lookingFor: "CHAT" as const, age: 36, interests: ["Gardening", "Art", "Podcasts"], bio: "Curious by nature, happiest near plants and an unhurried conversation.", occupation: "Editor", education: "Literature", languages: ["English", "Tamil"], relationshipIntent: "Companionship and conversation", onlineStatus: false },
  { key: "rohan", email: "rohan.demo@example.test", displayName: "Rohan Sen", gender: "MALE" as const, city: "Pune", maritalStatus: "MARRIED" as const, lookingFor: "FRIENDSHIP" as const, age: 42, interests: ["Cycling", "History"], bio: "Weekend cyclist and lifelong learner. Here for kind conversation.", occupation: "Teacher", education: "History", languages: ["English", "Marathi"], relationshipIntent: "New friendships", onlineStatus: true },
  { key: "tara", email: "tara.demo@example.test", displayName: "Tara Kapoor", gender: "NON_BINARY" as const, city: "Hyderabad", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 24, interests: ["Photography", "Theatre", "Coffee"], bio: "Finding beauty in ordinary places and people who notice the details.", occupation: "Photographer", education: "Fine arts", languages: ["English", "Telugu"], relationshipIntent: "Something intentional", onlineStatus: true },
  { key: "ishita", email: "ishita.demo@example.test", displayName: "Ishita Sharma", gender: "FEMALE" as const, city: "Mumbai", maritalStatus: "SINGLE" as const, lookingFor: "RELATIONSHIP" as const, age: 27, interests: ["Yoga", "Books", "Travel"], bio: "Warm conversations, weekend escapes, and a soft spot for old bookstores.", occupation: "Marketing strategist", education: "Business", languages: ["English", "Hindi"], relationshipIntent: "A steady, meaningful connection", onlineStatus: true },
  { key: "naina", email: "naina.demo@example.test", displayName: "Naina Verma", gender: "FEMALE" as const, city: "Bengaluru", maritalStatus: "SINGLE" as const, lookingFor: "CHAT" as const, age: 30, interests: ["Music", "Cooking", "Podcasts"], bio: "Good food, better playlists, and conversations that do not feel rushed.", occupation: "UX researcher", education: "Psychology", languages: ["English", "Hindi"], relationshipIntent: "Companionship and curiosity", onlineStatus: false },
  { key: "simran", email: "simran.demo@example.test", displayName: "Simran Gill", gender: "FEMALE" as const, city: "Delhi", maritalStatus: "DIVORCED" as const, lookingFor: "DATING" as const, age: 34, interests: ["Art", "Brunch", "Cinema"], bio: "Independent, cheerful, and always up for a thoughtful exchange.", occupation: "Gallery curator", education: "Fine arts", languages: ["English", "Hindi", "Punjabi"], relationshipIntent: "Something honest and unhurried", onlineStatus: true },
  { key: "avani", email: "avani.demo@example.test", displayName: "Avani Shah", gender: "FEMALE" as const, city: "Pune", maritalStatus: "SINGLE" as const, lookingFor: "MARRIAGE" as const, age: 29, interests: ["Dance", "Nature", "Photography"], bio: "Finding joy in small rituals, green spaces, and people with kind eyes.", occupation: "Product manager", education: "Engineering", languages: ["English", "Hindi", "Gujarati"], relationshipIntent: "A sincere long-term partnership", onlineStatus: false },
  { key: "riya", email: "riya.demo@example.test", displayName: "Riya Menon", gender: "FEMALE" as const, city: "Chennai", maritalStatus: "SINGLE" as const, lookingFor: "FRIENDSHIP" as const, age: 26, interests: ["Reading", "Beach walks", "Coffee"], bio: "Quietly optimistic, fond of coastal evenings and good questions.", occupation: "Content editor", education: "Literature", languages: ["English", "Tamil", "Malayalam"], relationshipIntent: "New friendships with depth", onlineStatus: true },
  { key: "kavya", email: "kavya.demo@example.test", displayName: "Kavya Nair", gender: "FEMALE" as const, city: "Kochi", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 28, interests: ["Food", "Travel", "Painting"], bio: "Always curious about new places, local food, and people who listen well.", occupation: "Interior designer", education: "Design", languages: ["English", "Malayalam"], relationshipIntent: "A genuine connection", onlineStatus: false },
  { key: "pihu", email: "pihu.demo@example.test", displayName: "Pihu Arora", gender: "FEMALE" as const, city: "Chandigarh", maritalStatus: "SINGLE" as const, lookingFor: "CHAT" as const, age: 25, interests: ["Dance", "Fashion", "Coffee"], bio: "Bright days, good music, and conversations that make time disappear.", occupation: "Brand consultant", education: "Commerce", languages: ["English", "Hindi"], relationshipIntent: "Easy, thoughtful conversation", onlineStatus: true },
  { key: "ananya", email: "ananya.demo@example.test", displayName: "Ananya Bose", gender: "FEMALE" as const, city: "Kolkata", maritalStatus: "DIVORCED" as const, lookingFor: "RELATIONSHIP" as const, age: 37, interests: ["Theatre", "Poetry", "History"], bio: "A lover of old cities, live theatre, and emotionally honest conversations.", occupation: "Museum educator", education: "History", languages: ["English", "Hindi", "Bengali"], relationshipIntent: "A mature and meaningful bond", onlineStatus: false },
  { key: "zoya", email: "zoya.demo@example.test", displayName: "Zoya Siddiqui", gender: "FEMALE" as const, city: "Lucknow", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 32, interests: ["Cooking", "Books", "Music"], bio: "Homemade food, late-night playlists, and a soft spot for kind people.", occupation: "Food writer", education: "Journalism", languages: ["English", "Hindi", "Urdu"], relationshipIntent: "Something warm and intentional", onlineStatus: true },
  { key: "manya", email: "manya.demo@example.test", displayName: "Manya Joshi", gender: "FEMALE" as const, city: "Indore", maritalStatus: "SINGLE" as const, lookingFor: "MARRIAGE" as const, age: 30, interests: ["Fitness", "Gardening", "Travel"], bio: "Grounded, optimistic, and happiest when planning the next weekend escape.", occupation: "Chartered accountant", education: "Finance", languages: ["English", "Hindi"], relationshipIntent: "A sincere life partnership", onlineStatus: false },
  { key: "shruti", email: "shruti.demo@example.test", displayName: "Shruti Kulkarni", gender: "FEMALE" as const, city: "Nagpur", maritalStatus: "SINGLE" as const, lookingFor: "FRIENDSHIP" as const, age: 27, interests: ["Cycling", "Podcasts", "Books"], bio: "A little introverted, very curious, and always ready for a long walk.", occupation: "Software engineer", education: "Computer science", languages: ["English", "Hindi", "Marathi"], relationshipIntent: "Friendship that feels natural", onlineStatus: false },
  { key: "leela", email: "leela.demo@example.test", displayName: "Leela Krishnan", gender: "FEMALE" as const, city: "Coimbatore", maritalStatus: "WIDOWED" as const, lookingFor: "CHAT" as const, age: 44, interests: ["Classical music", "Plants", "Reading"], bio: "Still finding new chapters, with a fondness for calm and considerate people.", occupation: "School principal", education: "Education", languages: ["English", "Tamil"], relationshipIntent: "Companionship and conversation", onlineStatus: false },
  { key: "sana", email: "sana.demo@example.test", displayName: "Sana Qureshi", gender: "FEMALE" as const, city: "Ahmedabad", maritalStatus: "SINGLE" as const, lookingFor: "RELATIONSHIP" as const, age: 29, interests: ["Photography", "Running", "Cinema"], bio: "Collecting little moments, city photographs, and honest conversations.", occupation: "Visual designer", education: "Media", languages: ["English", "Hindi", "Gujarati"], relationshipIntent: "A patient, genuine relationship", onlineStatus: true },
  { key: "diya", email: "diya.demo@example.test", displayName: "Diya Rao", gender: "FEMALE" as const, city: "Mysuru", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 26, interests: ["Baking", "Nature", "Movies"], bio: "Weekend baker, nature lover, and fan of people who keep things real.", occupation: "HR specialist", education: "Psychology", languages: ["English", "Kannada", "Hindi"], relationshipIntent: "A joyful, intentional connection", onlineStatus: true },
  { key: "aarohi", email: "aarohi.demo@example.test", displayName: "Aarohi Desai", gender: "FEMALE" as const, city: "Surat", maritalStatus: "SINGLE" as const, lookingFor: "CHAT" as const, age: 31, interests: ["Design", "Travel", "Tea"], bio: "A design enthusiast who appreciates slow evenings and thoughtful people.", occupation: "Graphic designer", education: "Visual communication", languages: ["English", "Hindi", "Gujarati"], relationshipIntent: "A comfortable, genuine beginning", onlineStatus: false },
  { key: "mira", email: "mira.demo@example.test", displayName: "Mira Sethi", gender: "FEMALE" as const, city: "Dubai", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 29, interests: ["Travel", "Architecture", "Coffee"], bio: "Based between cities, drawn to good design, warm conversations, and new places.", occupation: "Architect", education: "Architecture", languages: ["English", "Hindi"], relationshipIntent: "A relaxed but intentional connection", onlineStatus: true },
  { key: "tanvi", email: "tanvi.demo@example.test", displayName: "Tanvi Bhatia", gender: "FEMALE" as const, city: "Dubai", maritalStatus: "SINGLE" as const, lookingFor: "CHAT" as const, age: 26, interests: ["Films", "Music", "Reading"], bio: "A quiet observer who enjoys independent films and conversations with substance.", occupation: "Film editor", education: "Mass communication", languages: ["English", "Hindi", "Punjabi"], relationshipIntent: "A good conversation first", onlineStatus: false },
  { key: "suhani", email: "suhani.demo@example.test", displayName: "Suhani Rao", gender: "FEMALE" as const, city: "Mumbai", maritalStatus: "DIVORCED" as const, lookingFor: "RELATIONSHIP" as const, age: 35, interests: ["Art", "Theatre", "Classical music"], bio: "Art exhibitions, long drives, and a preference for honesty over performance.", occupation: "Art curator", education: "Fine arts", languages: ["English", "Hindi", "Marathi"], relationshipIntent: "A mature, meaningful relationship", onlineStatus: false },
  { key: "alia", email: "alia.demo@example.test", displayName: "Alia Khanna", gender: "FEMALE" as const, city: "Jaipur", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 24, interests: ["Fashion", "Street food", "Photography"], bio: "Always exploring a new lane, a new cafe, or a new way to frame a moment.", occupation: "Fashion stylist", education: "Fashion design", languages: ["English", "Hindi"], relationshipIntent: "Something spontaneous and sincere", onlineStatus: true },
  { key: "harini", email: "harini.demo@example.test", displayName: "Harini Krishnan", gender: "FEMALE" as const, city: "Goa", maritalStatus: "SINGLE" as const, lookingFor: "FRIENDSHIP" as const, age: 31, interests: ["Beach walks", "Cooking", "Yoga"], bio: "Sea air, homemade meals, and friendships that do not need constant maintenance.", occupation: "Wellness coach", education: "Nutrition", languages: ["English", "Tamil", "Malayalam"], relationshipIntent: "Kind new friendships", onlineStatus: false },
  { key: "lavanya", email: "lavanya.demo@example.test", displayName: "Lavanya Iyer", gender: "FEMALE" as const, city: "Dubai", maritalStatus: "SINGLE" as const, lookingFor: "MARRIAGE" as const, age: 30, interests: ["Travel", "Food", "Photography"], bio: "Curious, family-minded, and happiest when discovering a new corner of the world.", occupation: "Operations manager", education: "Business administration", languages: ["English", "Hindi", "Tamil"], relationshipIntent: "A sincere long-term partnership", onlineStatus: true },
  { key: "ishani", email: "ishani.demo@example.test", displayName: "Ishani Kapoor", gender: "FEMALE" as const, city: "Bengaluru", maritalStatus: "SINGLE" as const, lookingFor: "CHAT" as const, age: 33, interests: ["Rainy days", "Books", "Design"], bio: "Thoughtful, slightly introverted, and always ready for a conversation over chai.", occupation: "Service designer", education: "Design", languages: ["English", "Hindi"], relationshipIntent: "A comfortable beginning", onlineStatus: false },
  { key: "navya", email: "navya.demo@example.test", displayName: "Navya Mehra", gender: "FEMALE" as const, city: "Dubai", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 27, interests: ["Travel", "Running", "Coffee"], bio: "Finding balance between ambitious days, early runs, and unplanned city walks.", occupation: "Management consultant", education: "Economics", languages: ["English", "Hindi"], relationshipIntent: "An honest, active partnership", onlineStatus: true },
  { key: "trisha", email: "trisha.demo@example.test", displayName: "Trisha Sen", gender: "FEMALE" as const, city: "Delhi", maritalStatus: "WIDOWED" as const, lookingFor: "RELATIONSHIP" as const, age: 38, interests: ["Books", "History", "Museums"], bio: "A lifelong learner who values patience, wit, and the small details in a person.", occupation: "Researcher", education: "History", languages: ["English", "Hindi", "Bengali"], relationshipIntent: "A thoughtful and steady relationship", onlineStatus: false },
  { key: "radhika", email: "radhika.demo@example.test", displayName: "Radhika Menon", gender: "FEMALE" as const, city: "Kochi", maritalStatus: "SINGLE" as const, lookingFor: "FRIENDSHIP" as const, age: 30, interests: ["Nature", "Reading", "Travel"], bio: "Drawn to quiet mornings, green places, and people who are comfortable being themselves.", occupation: "Environmental consultant", education: "Environmental science", languages: ["English", "Malayalam"], relationshipIntent: "A genuine friendship with room to grow", onlineStatus: true },
  { key: "arjun", email: "arjun.demo@example.test", displayName: "Arjun Kapoor", gender: "MALE" as const, city: "Dubai", maritalStatus: "SINGLE" as const, lookingFor: "RELATIONSHIP" as const, age: 29, interests: ["Travel", "Architecture", "Running"], bio: "Curious about cities, early morning runs, and conversations that go beyond small talk.", occupation: "Urban planner", education: "Architecture", languages: ["English", "Hindi"], relationshipIntent: "A genuine relationship built slowly", onlineStatus: true },
  { key: "vihaan", email: "vihaan.demo@example.test", displayName: "Vihaan Mehta", gender: "MALE" as const, city: "Dubai", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 32, interests: ["Coffee", "Cinema", "Photography"], bio: "A calm person who enjoys good films, thoughtful people, and discovering hidden cafes.", occupation: "Product manager", education: "Computer science", languages: ["English", "Hindi", "Gujarati"], relationshipIntent: "Something easy, honest, and intentional", onlineStatus: false },
  { key: "aditya", email: "aditya.demo@example.test", displayName: "Aditya Malhotra", gender: "MALE" as const, city: "Goa", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 27, interests: ["Surfing", "Fitness", "Music"], bio: "Work hard, stay curious, and make time for the sea, live music, and good company.", occupation: "Fitness entrepreneur", education: "Business", languages: ["English", "Hindi"], relationshipIntent: "A fun connection with real potential", onlineStatus: true },
  { key: "ishaan", email: "ishaan.demo@example.test", displayName: "Ishaan Rathore", gender: "MALE" as const, city: "Jaipur", maritalStatus: "SINGLE" as const, lookingFor: "MARRIAGE" as const, age: 35, interests: ["History", "Cooking", "Travel"], bio: "Rooted in family, open to the world, and happiest when sharing a meal and a story.", occupation: "Heritage consultant", education: "History", languages: ["English", "Hindi"], relationshipIntent: "A sincere long-term partnership", onlineStatus: false },
  { key: "neel", email: "neel.demo@example.test", displayName: "Neel Shah", gender: "MALE" as const, city: "Bengaluru", maritalStatus: "SINGLE" as const, lookingFor: "CHAT" as const, age: 30, interests: ["Books", "Design", "Podcasts"], bio: "A thoughtful listener with a soft spot for bookstores, design, and long conversations.", occupation: "UX designer", education: "Design", languages: ["English", "Hindi", "Gujarati"], relationshipIntent: "A good conversation with room to grow", onlineStatus: false },
  { key: "rahul", email: "rahul.demo@example.test", displayName: "Rahul Bhatia", gender: "MALE" as const, city: "Dubai", maritalStatus: "DIVORCED" as const, lookingFor: "RELATIONSHIP" as const, age: 31, interests: ["Travel", "Food", "Cycling"], bio: "Grounded, optimistic, and always planning the next road trip or dinner with friends.", occupation: "Finance consultant", education: "Finance", languages: ["English", "Hindi", "Punjabi"], relationshipIntent: "A mature and kind relationship", onlineStatus: true },
  { key: "vikram", email: "vikram.demo@example.test", displayName: "Vikram Sethi", gender: "MALE" as const, city: "Mumbai", maritalStatus: "SINGLE" as const, lookingFor: "CHAT" as const, age: 28, interests: ["Music", "Rooftop cafes", "Reading"], bio: "Music on in the background, a book nearby, and a preference for honest conversations.", occupation: "Music producer", education: "Media", languages: ["English", "Hindi"], relationshipIntent: "Starting with a comfortable conversation", onlineStatus: false },
  { key: "rohit", email: "rohit.demo@example.test", displayName: "Rohit Anand", gender: "MALE" as const, city: "Delhi", maritalStatus: "SINGLE" as const, lookingFor: "RELATIONSHIP" as const, age: 36, interests: ["Art", "Museums", "Tennis"], bio: "Equal parts practical and curious, with a weakness for galleries and weekend tennis.", occupation: "Investment analyst", education: "Economics", languages: ["English", "Hindi"], relationshipIntent: "A thoughtful, steady relationship", onlineStatus: false },
  { key: "manav", email: "manav.demo@example.test", displayName: "Manav Joshi", gender: "MALE" as const, city: "Pune", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 25, interests: ["Cycling", "Baking", "Movies"], bio: "An easygoing cyclist who believes the best plans usually include good food.", occupation: "Software engineer", education: "Computer science", languages: ["English", "Hindi", "Marathi"], relationshipIntent: "Something joyful and genuine", onlineStatus: true },
  { key: "samar", email: "samar.demo@example.test", displayName: "Samar Menon", gender: "MALE" as const, city: "Kochi", maritalStatus: "WIDOWED" as const, lookingFor: "FRIENDSHIP" as const, age: 40, interests: ["Nature", "Cooking", "Classical music"], bio: "A calm, considerate person who enjoys nature, music, and meaningful companionship.", occupation: "School administrator", education: "Education", languages: ["English", "Malayalam", "Tamil"], relationshipIntent: "A genuine companionship", onlineStatus: false },
  { key: "yuvraj", email: "yuvraj.demo@example.test", displayName: "Yuvraj Arora", gender: "MALE" as const, city: "Dubai", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 28, interests: ["Fitness", "Travel", "Coffee"], bio: "Disciplined about training, relaxed about everything else, and always up for a good coffee.", occupation: "Sports physiotherapist", education: "Physiotherapy", languages: ["English", "Hindi", "Punjabi"], relationshipIntent: "A confident but genuine connection", onlineStatus: true },
  { key: "veer", email: "veer.demo@example.test", displayName: "Veer Khanna", gender: "MALE" as const, city: "Goa", maritalStatus: "SINGLE" as const, lookingFor: "RELATIONSHIP" as const, age: 31, interests: ["Fitness", "Beach walks", "Music"], bio: "A steady person who enjoys the sea, live music, and making time for the people he cares about.", occupation: "Startup founder", education: "Business", languages: ["English", "Hindi"], relationshipIntent: "A meaningful relationship with mutual effort", onlineStatus: false },
  { key: "aaryan", email: "aaryan.demo@example.test", displayName: "Aaryan Deshmukh", gender: "MALE" as const, city: "Pune", maritalStatus: "SINGLE" as const, lookingFor: "CHAT" as const, age: 26, interests: ["Running", "Movies", "Cooking"], bio: "Training for the next race, learning to cook better, and looking for conversations that feel easy.", occupation: "Civil engineer", education: "Engineering", languages: ["English", "Hindi", "Marathi"], relationshipIntent: "A natural start with real potential", onlineStatus: true },
  { key: "dev", email: "dev.demo@example.test", displayName: "Dev Malhotra", gender: "MALE" as const, city: "Jaipur", maritalStatus: "PREFER_NOT_TO_SAY" as const, lookingFor: "CHAT" as const, age: 22, interests: ["Gaming", "Music", "Technology"], bio: "Curious, easygoing, and here for conversations that feel natural.", occupation: "Software developer", education: "Computer science", languages: ["English", "Hindi"], relationshipIntent: "A comfortable conversation with room to grow", onlineStatus: false },
  { key: "isha", email: "isha.resort.demo@example.test", displayName: "Isha Kapoor", gender: "FEMALE" as const, city: "Goa", maritalStatus: "SINGLE" as const, lookingFor: "DATING" as const, age: 29, interests: ["Travel", "Swimming", "Cinema"], bio: "Drawn to sunny places, honest conversations, and people who make room for laughter.", occupation: "Brand strategist", education: "Marketing", languages: ["English", "Hindi"], relationshipIntent: "A warm, intentional connection", onlineStatus: true },
  { key: "anika", email: "anika.resort.demo@example.test", displayName: "Anika Rao", gender: "FEMALE" as const, city: "Mumbai", maritalStatus: "SINGLE" as const, lookingFor: "RELATIONSHIP" as const, age: 30, interests: ["Architecture", "Travel", "Books"], bio: "A calm optimist who loves thoughtful design, slow evenings, and conversations with depth.", occupation: "Architect", education: "Architecture", languages: ["English", "Hindi", "Marathi"], relationshipIntent: "A mature relationship built with care", onlineStatus: false },
];
const memberUsers = [
  ["Aanya Sharma", "15 May 2002", "SINGLE", "Delhi", "aanya.sharma2402@gmail.com", "Creative soul who loves weekend getaways and good conversations.", "Serious relationship", ["Travel", "Photography", "Music"], "RELATIONSHIP"],
  ["Meera Kapoor", "22 Feb 1999", "SINGLE", "Mumbai", "meera.kapoor2799@gmail.com", "Ambitious professional with a soft spot for coffee and books.", "Long-term relationship", ["Reading", "Cafés", "Fitness"], "RELATIONSHIP"],
  ["Kavya Singh", "8 Aug 2003", "SINGLE", "Jaipur", "kavya.singh2303@gmail.com", "Easygoing, cheerful and always looking for new experiences.", "Meaningful connection", ["Dance", "Travel", "Movies"], "DATING"],
  ["Riya Malhotra", "19 Jan 1997", "DIVORCED", "Chandigarh", "riya.malhotra2997@gmail.com", "Independent and mature, looking for a fresh start in life.", "Serious relationship", ["Cooking", "Wellness", "Gardening"], "RELATIONSHIP"],
  ["Ananya Verma", "3 Nov 2000", "SINGLE", "Lucknow", "ananya.verma2500@gmail.com", "Loves exploring new places and making lasting memories.", "Long-term relationship", ["Travel", "Food", "Photography"], "RELATIONSHIP"],
  ["Ishita Gupta", "27 Jun 2000", "SINGLE", "Bengaluru", "ishita.gupta2600@gmail.com", "Tech enthusiast who enjoys quiet evenings and deep talks.", "Serious relationship", ["Technology", "Books", "Hiking"], "RELATIONSHIP"],
  ["Nisha Patel", "11 Apr 1995", "SINGLE", "Ahmedabad", "nisha.patel3195@gmail.com", "Confident, family-oriented and enjoys a balanced lifestyle.", "Meaningful connection", ["Cooking", "Yoga", "Music"], "RELATIONSHIP"],
  ["Pooja Mehta", "6 Dec 1997", "WIDOWED", "Pune", "pooja.mehta2897@gmail.com", "Kind-hearted and optimistic, ready to meet someone genuine.", "Companionship", ["Gardening", "Music", "Travel"], "CHAT"],
  ["Simran Kaur", "14 Sep 2003", "SINGLE", "Amritsar", "simran.kaur2203@gmail.com", "Young, energetic and passionate about creativity.", "Dating with intention", ["Art", "Dance", "Fashion"], "DATING"],
  ["Tara Joshi", "25 Mar 1996", "SINGLE", "Hyderabad", "tara.joshi3096@gmail.com", "Career-focused but believes in making time for love.", "Long-term relationship", ["Fitness", "Travel", "Podcasts"], "RELATIONSHIP"],
  ["Sneha Reddy", "9 Jul 2002", "SINGLE", "Chennai", "sneha.reddy2402@gmail.com", "Warm, friendly and a fan of spontaneous plans.", "Serious relationship", ["Music", "Food", "Beach trips"], "RELATIONSHIP"],
  ["Diya Agarwal", "18 Oct 1999", "SINGLE", "Kolkata", "diya.agarwal2699@gmail.com", "Loves art, meaningful conversations and discovering hidden cafés.", "Meaningful connection", ["Art", "Cafés", "Reading"], "RELATIONSHIP"],
  ["Neha Bansal", "2 Feb 1994", "DIVORCED", "Gurugram", "neha.bansal3294@gmail.com", "Strong, independent and looking for a compatible partner.", "Serious relationship", ["Travel", "Fitness", "Cooking"], "RELATIONSHIP"],
  ["Alisha Khan", "30 Nov 2002", "SINGLE", "Bhopal", "alisha.khan2302@gmail.com", "Curious, expressive and enjoys meeting people from different backgrounds.", "Dating with intention", ["Movies", "Music", "Languages"], "DATING"],
  ["Mahi Sethi", "17 Jan 2001", "SINGLE", "Noida", "mahi.sethi2501@gmail.com", "Simple, positive and believes the little things matter.", "Long-term relationship", ["Cooking", "Shopping", "Nature"], "RELATIONSHIP"],
  ["Sanya Chawla", "21 May 1998", "SINGLE", "Dehradun", "sanya.chawla2898@gmail.com", "Outdoor lover who enjoys peaceful places and good company.", "Serious relationship", ["Hiking", "Travel", "Photography"], "RELATIONSHIP"],
  ["Kritika Roy", "4 Aug 1999", "SINGLE", "Kolkata", "kritika.roy2799@gmail.com", "Creative professional with a love for culture and conversations.", "Meaningful connection", ["Design", "Music", "Museums"], "RELATIONSHIP"],
  ["Avni Thakur", "12 Dec 2004", "SINGLE", "Shimla", "avni.thakur2104@gmail.com", "Cheerful student who loves learning and exploring.", "Casual dating", ["Books", "Art", "Travel"], "DATING"],
  ["Sakshi Jain", "7 Mar 1993", "SEPARATED", "Indore", "sakshi.jain3393@gmail.com", "Emotionally mature and looking for an honest connection.", "Serious relationship", ["Wellness", "Reading", "Travel"], "RELATIONSHIP"],
  ["Zoya Ali", "26 Oct 2001", "SINGLE", "Hyderabad", "zoya.ali2401@gmail.com", "Adventurous, open-minded and enjoys trying new things.", "Long-term relationship", ["Food", "Travel", "Music"], "RELATIONSHIP"],
  ["Esha Tiwari", "16 Apr 2000", "SINGLE", "Varanasi", "esha.tiwari2600@gmail.com", "A thoughtful person who enjoys meaningful conversations and peaceful evenings.", "Serious relationship", ["Reading", "Music", "Travel"], "RELATIONSHIP"],
  ["Myra Arora", "5 Sep 1997", "SINGLE", "Delhi", "myra.arora2997@gmail.com", "Stylish, ambitious and always up for a new adventure.", "Long-term relationship", ["Fashion", "Fitness", "Travel"], "RELATIONSHIP"],
  ["Aditi Nair", "23 Dec 2001", "SINGLE", "Kochi", "aditi.nair2401@gmail.com", "Calm, curious and loves discovering new food and places.", "Meaningful connection", ["Cooking", "Food", "Photography"], "RELATIONSHIP"],
  ["Lavanya Mishra", "10 Jun 1996", "DIVORCED", "Kanpur", "lavanya.mishra3096@gmail.com", "Independent and optimistic, looking for a genuine partnership.", "Serious relationship", ["Gardening", "Movies", "Wellness"], "RELATIONSHIP"],
  ["Radhika Das", "28 Jan 1999", "SINGLE", "Bhubaneswar", "radhika.das2799@gmail.com", "Friendly, creative and enjoys celebrating life's small moments.", "Long-term relationship", ["Art", "Music", "Cooking"], "RELATIONSHIP"],
  ["Kiara Oberoi", "13 Oct 2000", "SINGLE", "Mumbai", "kiara.oberoi2500@gmail.com", "Outgoing, confident and passionate about exploring the world.", "Dating with intention", ["Travel", "Dance", "Shopping"], "DATING"],
  ["Shruti Iyer", "9 Mar 1994", "SEPARATED", "Bengaluru", "shruti.iyer3294@gmail.com", "Mature, warm and values honesty, trust and companionship.", "Serious relationship", ["Yoga", "Books", "Nature"], "RELATIONSHIP"],
].map((item, index) => ({ number: index + 1, displayName: item[0] as string, dateOfBirth: item[1] as string, maritalStatus: item[2] as "SINGLE", city: item[3] as string, email: item[4] as string, bio: item[5] as string, relationshipIntent: item[6] as string, interests: item[7] as string[], lookingFor: item[8] as "CHAT" | "DATING" | "RELATIONSHIP" }));
const demoImageByKey: Record<string, string> = { ishita: "/demo-profiles/ishita.png", naina: "/demo-profiles/naina.png", simran: "/demo-profiles/simran.png", avani: "/demo-profiles/avani.png", riya: "/demo-profiles/riya.png", kavya: "/demo-profiles/kavya.png", pihu: "/demo-profiles/pihu.png", ananya: "/demo-profiles/ananya.png", zoya: "/demo-profiles/zoya.png", manya: "/demo-profiles/manya.png", shruti: "/demo-profiles/shruti.png", leela: "/demo-profiles/leela.png", sana: "/demo-profiles/sana.png", diya: "/demo-profiles/ishita.png", aarohi: "/demo-profiles/naina.png", mira: "/demo-profiles/mira.png", tanvi: "/demo-profiles/tanvi.png", suhani: "/demo-profiles/suhani.png", alia: "/demo-profiles/alia.png", harini: "/demo-profiles/harini.png", lavanya: "/demo-profiles/lavanya.png", ishani: "/demo-profiles/ishani.png", navya: "/demo-profiles/navya.png", trisha: "/demo-profiles/trisha.png", radhika: "/demo-profiles/radhika.png", arjun: "/demo-profiles/arjun.png", vihaan: "/demo-profiles/vihaan.png", aditya: "/demo-profiles/aditya.png", ishaan: "/demo-profiles/ishaan.png", neel: "/demo-profiles/neel.png", rahul: "/demo-profiles/rahul.png", vikram: "/demo-profiles/vikram.png", rohit: "/demo-profiles/rohit.png", manav: "/demo-profiles/manav.png", samar: "/demo-profiles/samar.png", yuvraj: "/demo-profiles/yuvraj.png", veer: "/demo-profiles/veer.png", aaryan: "/demo-profiles/aaryan.png" };
demoImageByKey.isha = "/demo-profiles/isha-resort.png";
demoImageByKey.anika = "/demo-profiles/anika-resort.png";

async function upsertPlan(input: { name: string; code: string; durationMonths: number; price: number; featured: boolean; sortOrder: number }) {
  return prisma.subscriptionPlan.upsert({ where: { code: input.code }, update: input, create: { ...input, currency: "INR", description: `Demo ${input.name} membership.` } });
}

async function main() {
  const adminEmail = process.env.ADMIN_EMAIL?.trim().toLowerCase();
  const adminPassword = process.env.ADMIN_INITIAL_PASSWORD;
  if (!adminEmail || !adminPassword) throw new Error("ADMIN_EMAIL and ADMIN_INITIAL_PASSWORD are required to run the seed");
  if (adminPassword.length < 12) throw new Error("ADMIN_INITIAL_PASSWORD must be at least 12 characters");

  const passwordHash = await bcrypt.hash(demoPassword, 12);
  const users = new Map<string, { id: string }>();
  for (const item of demoUsers) {
    const user = await prisma.user.upsert({
      where: { email: item.email },
      update: { displayName: item.displayName, gender: item.gender, city: item.city, maritalStatus: item.maritalStatus, lookingFor: item.lookingFor, isEmailVerified: true, status: item.key === "dev" ? "ACTIVE" : "ACTIVE", termsVersion: TERMS_VERSION, acceptedAt: new Date() },
      create: { email: item.email, passwordHash, displayName: item.displayName, dateOfBirth: dob(item.age, 6, 15), gender: item.gender, city: item.city, maritalStatus: item.maritalStatus, lookingFor: item.lookingFor, isEmailVerified: true, status: "ACTIVE", termsVersion: TERMS_VERSION, acceptedAt: new Date() },
      select: { id: true },
    });
    users.set(item.key, user);
    const profileImageUrl = demoImageByKey[item.key] ?? "/og-image.png";
    await prisma.profile.upsert({ where: { userId: user.id }, update: { bio: item.bio, profileImageUrls: [profileImageUrl], interests: item.interests, occupation: item.occupation, education: item.education, languages: item.languages, relationshipIntent: item.relationshipIntent, genderPreference: item.key === "aanya" ? "MALE" : null, agePreferenceMin: 24, agePreferenceMax: 45, locationPreference: item.city, lookingFor: item.lookingFor, visibility: "VISIBLE", showOnlineStatus: true, onlineStatus: item.onlineStatus, allowInterests: true }, create: { userId: user.id, profileImageUrls: [profileImageUrl], bio: item.bio, interests: item.interests, occupation: item.occupation, education: item.education, languages: item.languages, relationshipIntent: item.relationshipIntent, genderPreference: item.key === "aanya" ? "MALE" : null, agePreferenceMin: 24, agePreferenceMax: 45, locationPreference: item.city, lookingFor: item.lookingFor, visibility: "VISIBLE", showOnlineStatus: true, onlineStatus: item.onlineStatus, allowInterests: true } });
    await prisma.notificationPreference.upsert({ where: { userId: user.id }, update: {}, create: { userId: user.id } });
  }

  for (const item of memberUsers) {
    const user = await prisma.user.upsert({
      where: { email: item.email },
      update: { displayName: item.displayName, dateOfBirth: new Date(`${item.dateOfBirth} 00:00:00`), gender: "FEMALE", city: item.city, maritalStatus: item.maritalStatus, lookingFor: item.lookingFor, isEmailVerified: true, status: "ACTIVE", termsVersion: TERMS_VERSION, acceptedAt: new Date() },
      create: { email: item.email, passwordHash: await bcrypt.hash(crypto.randomBytes(24).toString("hex"), 12), displayName: item.displayName, dateOfBirth: new Date(`${item.dateOfBirth} 00:00:00`), gender: "FEMALE", city: item.city, maritalStatus: item.maritalStatus, lookingFor: item.lookingFor, isEmailVerified: true, status: "ACTIVE", termsVersion: TERMS_VERSION, acceptedAt: new Date() },
      select: { id: true },
    });
    const image = `/member-profiles/${28 - item.number}.png`;
    await prisma.profile.upsert({
      where: { userId: user.id },
      update: { bio: item.bio, profileImageUrls: [image], interests: item.interests, languages: ["English", "Hindi"], relationshipIntent: item.relationshipIntent, agePreferenceMin: 21, agePreferenceMax: 45, locationPreference: item.city, lookingFor: item.lookingFor, visibility: "VISIBLE", showOnlineStatus: true, onlineStatus: true, allowInterests: true },
      create: { userId: user.id, bio: item.bio, profileImageUrls: [image], interests: item.interests, languages: ["English", "Hindi"], relationshipIntent: item.relationshipIntent, agePreferenceMin: 21, agePreferenceMax: 45, locationPreference: item.city, lookingFor: item.lookingFor, visibility: "VISIBLE", showOnlineStatus: true, onlineStatus: true, allowInterests: true },
    });
    await prisma.notificationPreference.upsert({ where: { userId: user.id }, update: {}, create: { userId: user.id } });
  }

  if (process.env.SEED_ONLY_DEMO_PROFILES === "true") {
    console.log(`Upserted ${demoUsers.length} demo profiles only.`);
    return;
  }

  const [monthly, quarterly, yearly] = await Promise.all([
    upsertPlan({ name: "Monthly", code: "monthly", durationMonths: 1, price: 499, featured: false, sortOrder: 1 }),
    upsertPlan({ name: "Quarterly", code: "quarterly", durationMonths: 3, price: 999, featured: true, sortOrder: 2 }),
    upsertPlan({ name: "Yearly", code: "yearly", durationMonths: 12, price: 2499, featured: false, sortOrder: 3 }),
  ]);

  const adminHash = await bcrypt.hash(adminPassword, 12);
  await prisma.user.upsert({ where: { email: adminEmail }, update: { role: "ADMIN", isEmailVerified: true, status: "ACTIVE", termsVersion: TERMS_VERSION, acceptedAt: new Date() }, create: { email: adminEmail, passwordHash: adminHash, displayName: "Site Administrator", dateOfBirth: dob(35, 1, 1), gender: "PREFER_NOT_TO_SAY", isEmailVerified: true, role: "ADMIN", status: "ACTIVE", termsVersion: TERMS_VERSION, acceptedAt: new Date() } });

  const now = new Date();
  const subscriptions = [
    ["aanya", monthly, "ACTIVE", -15, 15], ["kabir", quarterly, "ACTIVE", -45, 45], ["meera", yearly, "EXPIRED", -400, -35], ["rohan", monthly, "PENDING", 0, 30], ["tara", quarterly, "CANCELLED", -20, 70],
  ] as const;
  for (const [key, plan, status, startOffset, endOffset] of subscriptions) {
    const user = users.get(key)!;
    const startDate = new Date(now.getTime() + startOffset * 86400000);
    const endDate = new Date(now.getTime() + endOffset * 86400000);
    const existing = await prisma.subscription.findFirst({ where: { userId: user.id, planId: plan.id } });
    const subscription = existing ? await prisma.subscription.update({ where: { id: existing.id }, data: { status, startDate, endDate, autoRenew: status === "ACTIVE" } }) : await prisma.subscription.create({ data: { userId: user.id, planId: plan.id, status, startDate, endDate, autoRenew: status === "ACTIVE" } });
    if (status === "ACTIVE" || status === "EXPIRED") await prisma.payment.upsert({ where: { razorpayPaymentId: `demo_payment_${key}` }, update: { userId: user.id, planId: plan.id, subscriptionId: subscription.id, amount: plan.price, currency: "INR", status: "SUCCESS", paidAt: startDate }, create: { id: `demo_payment_${key}`, userId: user.id, planId: plan.id, subscriptionId: subscription.id, amount: plan.price, currency: "INR", status: "SUCCESS", razorpayPaymentId: `demo_payment_${key}`, paidAt: startDate } });
  }

  const aanya = users.get("aanya")!; const kabir = users.get("kabir")!; const meera = users.get("meera")!; const tara = users.get("tara")!;
  const interest = await prisma.interest.upsert({ where: { senderId_receiverId: { senderId: kabir.id, receiverId: aanya.id } }, update: { status: "ACCEPTED", respondedAt: now }, create: { senderId: kabir.id, receiverId: aanya.id, status: "ACCEPTED", respondedAt: now, note: "Your profile made me curious." } });
  await prisma.interest.upsert({ where: { senderId_receiverId: { senderId: meera.id, receiverId: aanya.id } }, update: { status: "PENDING" }, create: { senderId: meera.id, receiverId: aanya.id, status: "PENDING" } });
  await prisma.interest.upsert({ where: { senderId_receiverId: { senderId: tara.id, receiverId: aanya.id } }, update: { status: "REJECTED", respondedAt: now }, create: { senderId: tara.id, receiverId: aanya.id, status: "REJECTED", respondedAt: now } });

  const pair = kabir.id < aanya.id ? { firstUserId: kabir.id, secondUserId: aanya.id } : { firstUserId: aanya.id, secondUserId: kabir.id };
  const match = await prisma.match.upsert({ where: { firstUserId_secondUserId: pair }, update: {}, create: pair });
  const conversation = await prisma.conversation.upsert({ where: { matchId: match.id }, update: {}, create: { matchId: match.id, members: { connect: [{ id: aanya.id }, { id: kabir.id }] } } });
  await prisma.message.upsert({ where: { id: "demo_message_hello" }, update: {}, create: { id: "demo_message_hello", conversationId: conversation.id, senderId: kabir.id, content: "Hello Aanya, your profile sounds like a good conversation.", type: "TEXT", deliveredAt: now, readAt: now } });
  await prisma.message.upsert({ where: { id: "demo_message_reply" }, update: {}, create: { id: "demo_message_reply", conversationId: conversation.id, senderId: aanya.id, content: "That is a lovely way to start. How is your week going?", type: "TEXT", deliveredAt: now } });
  await prisma.conversation.update({ where: { id: conversation.id }, data: { lastMessageAt: now } });
  await prisma.notification.deleteMany({ where: { userId: aanya.id, metadata: { path: ["seed"], equals: true } } });
  await prisma.notification.create({ data: { userId: aanya.id, type: "INTEREST_RECEIVED", title: "New interest", body: "Meera Iyer sent you an interest.", metadata: { seed: true } } });
  await prisma.notification.create({ data: { userId: kabir.id, type: "NEW_MATCH", title: "New match", body: "You and Aanya Mehta can now start a private conversation.", metadata: { seed: true } } });

  await prisma.siteSetting.upsert({ where: { key: "business_model" }, update: {}, create: { key: "business_model", value: "MEN_PAID_WOMEN_FREE", description: "Controls which members require paid access." } });
  console.log(`Seeded ${demoUsers.length} fictional demo users, three plans, subscriptions, interests, a match, a conversation, messages, and notifications.`);
  console.log(`Demo login password: ${demoPassword}${process.env.DEMO_INITIAL_PASSWORD ? " (from DEMO_INITIAL_PASSWORD)" : " (generated for this run)"}`);
  console.log(`Admin account: ${adminEmail} (password supplied through ADMIN_INITIAL_PASSWORD)`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(async () => { await prisma.$disconnect(); });
